In [1]:
import numpy as np
import pandas as pd
# import adata
import matplotlib.pyplot as plt
import seaborn as sns
import scanpy as sc
import os
import datetime
import argparse
import torch
from utils import *
from torch.utils.data import DataLoader
import episcanpy.api as epi

## Loading data

For more information check this [link](https://openproblems.bio/neurips_docs/about_tasks/task3_joint_embedding/)

In [2]:
# data
# !ls ~/arc_00077/raw_data/phase2-data/joint_embedding/openproblems_bmmc_multiome_phase2
# ! cd ~/arc_00077/raw_data/phase2-data/joint_embedding/openproblems_bmmc_multiome_phase2
! ls /user/leuven/331/vsc33180/arc_00077/raw_data/phase2-data/joint_embedding/openproblems_bmmc_multiome_phase2

openproblems_bmmc_multiome_phase2.censor_dataset.output_mod1.h5ad
openproblems_bmmc_multiome_phase2.censor_dataset.output_mod2.h5ad
openproblems_bmmc_multiome_phase2.censor_dataset.output_solution.h5ad


In [3]:
os.listdir("/user/leuven/331/vsc33180/arc_00077/raw_data/phase2-data/joint_embedding/openproblems_bmmc_multiome_phase2/")

['openproblems_bmmc_multiome_phase2.censor_dataset.output_mod1.h5ad',
 'openproblems_bmmc_multiome_phase2.censor_dataset.output_mod2.h5ad',
 'openproblems_bmmc_multiome_phase2.censor_dataset.output_solution.h5ad']

In [4]:
data_folder_path = "/user/leuven/331/vsc33180/arc_00077/raw_data/phase2-data/joint_embedding/openproblems_bmmc_multiome_phase2/"
files = os.listdir(data_folder_path)
# print(data_folder_path + files[0])
data1 = sc.read_h5ad(data_folder_path + files[0])
data2 = sc.read(data_folder_path + files[1])
# data3 = sc.read(data_folder_path + files[2])

Only considering the two last: ['.output_mod2', '.h5ad'].
Only considering the two last: ['.output_mod2', '.h5ad'].


In [5]:
print(data1)
print(data2)

AnnData object with n_obs × n_vars = 42492 × 13431
    obs: 'batch', 'size_factors'
    var: 'gene_ids', 'feature_types'
    uns: 'dataset_id', 'organism'
    layers: 'counts'
AnnData object with n_obs × n_vars = 42492 × 116490
    obs: 'batch'
    var: 'feature_types'
    uns: 'dataset_id', 'gene_activity_var_names', 'organism'
    obsm: 'gene_activity'
    layers: 'counts'


In [6]:
# print(data1.var["feature_types"])
rna = pd.DataFrame.sparse.from_spmatrix(data1.X) # 42492 x 13431
rna.columns = data1.var.index #data1.var["gene_ids"] -> ENSEMBL IDs

sc.pp.highly_variable_genes(data1, n_top_genes=5000) # Find HGVs
rna = rna.transpose().loc[data1.var["highly_variable"] == True].transpose()
rna.head() # 42492 x 5000

LINC01128  KLHL17  ISG15  C1orf159    CDK11B  SLC35E2B  CDK11A  PEX10  \
0        0.0     0.0    0.0       0.0  0.000000       0.0     0.0    0.0   
1        0.0     0.0    0.0       0.0  1.161511       0.0     0.0    0.0   
2        0.0     0.0    0.0       0.0  0.000000       0.0     0.0    0.0   
3        0.0     0.0    0.0       0.0  0.000000       0.0     0.0    0.0   
4        0.0     0.0    0.0       0.0  0.000000       0.0     0.0    0.0   

   PLCH2  TPRG1L  ...   MT-ATP8   MT-ATP6    MT-CO3    MT-ND3   MT-ND4L  \
0    0.0     0.0  ...  0.000000  0.000000  0.000000  1.688304  0.000000   
1    0.0     0.0  ...  0.000000  0.000000  1.161511  0.000000  0.000000   
2    0.0     0.0  ...  0.344029  0.599516  1.455109  0.344029  0.344029   
3    0.0     0.0  ...  0.000000  1.355826  2.527316  0.000000  0.000000   
4    0.0     0.0  ...  0.000000  1.556855  2.646429  1.054988  0.000000   

     MT-ND4    MT-ND5    MT-ND6    MT-CYB  AL592183.1  
0  1.688304  0.000000  0.000000  1.688304         0.0  
1  0.000000  0.000000  0.000000  2.651025         0.0  
2  0.599516  0.802834  0.344029  1.455109         0.0  
3  0.000000  1.911013  0.000000  0.000000         0.0  
4  1.556855  1.054988  0.000000  2.337923         0.0  

[5 rows x 5000 columns]

In [7]:
epi.pp.select_var_feature(data2, nb_features=10000, show=False) # Inplace select 10000 variable regions
atac = pd.DataFrame.sparse.from_spmatrix(data2.X)
atac.columns = data2.var.index
atac.head() # 42492 x 10002

chr1-629497-630394  chr1-633515-634474  chr1-778276-779191  \
0                 0.0                 1.0                 0.0   
1                 1.0                 1.0                 0.0   
2                 0.0                 1.0                 0.0   
3                 0.0                 0.0                 0.0   
4                 0.0                 1.0                 0.0   

   chr1-827067-827948  chr1-958865-959755  chr1-1013003-1013921  \
0                 0.0                 0.0                   0.0   
1                 1.0                 0.0                   0.0   
2                 0.0                 1.0                   1.0   
3                 0.0                 0.0                   1.0   
4                 0.0                 1.0                   0.0   

   chr1-1019151-1019993  chr1-1032734-1033630  chr1-1059182-1060025  \
0                   0.0                   0.0                   1.0   
1                   1.0                   0.0                   0.0   
2                   0.0                   0.0                   0.0   
3                   0.0                   0.0                   0.0   
4                   0.0                   0.0                   0.0   

   chr1-1068898-1069703  ...  chrX-154478646-154479538  \
0                   0.0  ...                       1.0   
1                   0.0  ...                       0.0   
2                   0.0  ...                       0.0   
3                   1.0  ...                       0.0   
4                   1.0  ...                       0.0   

   chrX-154490306-154491212  chrX-154515887-154516793  \
0                       0.0                       0.0   
1                       0.0                       0.0   
2                       0.0                       0.0   
3                       0.0                       0.0   
4                       0.0                       0.0   

   chrX-154546772-154547705  chrX-154762342-154763226  \
0                       0.0                       0.0   
1                       0.0                       0.0   
2                       0.0                       1.0   
3                       0.0                       0.0   
4                       0.0                       0.0   

   chrX-155026531-155027401  chrX-155070906-155071798  \
0                       0.0                       0.0   
1                       0.0                       0.0   
2                       1.0                       0.0   
3                       0.0                       0.0   
4                       0.0                       0.0   

   chrX-155215991-155216852  GL000219.1-99257-100160  KI270713.1-21434-22336  
0                       0.0                      1.0                     0.0  
1                       0.0                      0.0                     0.0  
2                       0.0                      0.0                     0.0  
3                       0.0                      0.0                     0.0  
4                       0.0                      0.0                     0.0  

[5 rows x 10002 columns]

## Setting up the necessary arguments and functions

In [8]:
# %tb
# # Model Settings =================================================================================================
# parser = argparse.ArgumentParser(description='Gen-RKM Model')

# parser.add_argument('--N', type=int, default=1000, help='Total # of samples')
# parser.add_argument('--mb_size', type=int, default=300, help='Mini-batch size. See utils.py')
# parser.add_argument('--h_dim', type=int, default=2, help='Dim of latent vector') # shared latent space
# parser.add_argument('--capacity', type=int, default=32, help='Capacity of network. See utils.py') # important in CNNs
# parser.add_argument('--x_fdim', type=int, default=128, help='Input x_fdim. See utils.py') # feature map dimensionality
# parser.add_argument('--y_fdim', type=int, default=20, help='Input y_fdim. See utils.py') # feature map dimensionality
# parser.add_argument('--c_accu', type=float, default=100, help='Input weight on recons_error')

# # Training Settings =============================
# parser.add_argument('--lr', type=float, default=1e-4, help='Input learning rate for optimizer')
# parser.add_argument('--max_epochs', type=int, default=100, help='Input max_epoch for cut-off')
# # parser.add_argument('--device', type=str, default='cuda', help='Device type: cuda or cpu')
# parser.add_argument('--device', type=str, default='cuda' if torch.cuda.is_available() else 'cpu', help='Device type: cuda or cpu')
# parser.add_argument('--workers', type=int, default=0, help='# of workers for dataloader')
# parser.add_argument('--shuffle', type=bool, default=True, help='shuffle dataset: true or false')

# opt = parser.parse_args()
args = {
    "N": rna.shape[0],
#     "mb_size": 300,
    "h_dim": 32,
    "capacity": 32,
    "x_fdim": 128,
    "y_fdim": 256,
    "c_accu": 100,
    "lr": 1e-6,
    "max_epochs": 1,
    "device": torch.device("cuda" if torch.cuda.is_available() else "cpu"),
    "workers": 15,
    "shuffle": True,
    "batch_size": 100,
}
opt = args
# print(opt["mb_size"])

In [9]:
def kPCA(X, Y):
#     print(X)
#     print(Y)
    a = torch.mm(X, torch.t(X)) + torch.mm(Y, torch.t(Y))
    nh1 = a.size(0)
    oneN = torch.div(torch.ones(nh1, nh1), nh1).float().to(opt["device"])
    a = a - torch.mm(oneN, a) - torch.mm(a, oneN) + torch.mm(torch.mm(oneN, a), oneN)  # centering
    print(a)
#     print(a, end="\r")
    h, s, _ = torch.svd(a, some=False)
    return h[:, :opt["h_dim"]], s

In [10]:
# Energy function
def rkm_loss(output1, X, output2, Y):
    h, s = kPCA(output1, output2)
    U = torch.mm(torch.t(output1), h)
    V = torch.mm(torch.t(output2), h)

    x_tilde = net3(torch.mm(h, torch.t(U))) # NET3
    y_tilde = net4(torch.mm(h, torch.t(V))) # NET4

    # Costs
    f1 = torch.trace(torch.mm(torch.mm(output1, U), torch.t(h))) + torch.trace(
        torch.mm(torch.mm(output2, V), torch.t(h)))
    f2 = 0.5 * torch.trace(torch.mm(h, torch.mm(torch.diag(s[:opt["h_dim"]]), torch.t(h))))
    f3 = 0.5 * ((torch.trace(torch.mm(torch.t(U), U))) + (torch.trace(torch.mm(torch.t(V), V))))
    recon_loss = torch.nn.MSELoss()
    f4 = recon_loss(x_tilde, X) + recon_loss(y_tilde, Y)  # reconstruction loss

    loss = - f1 + f3 + f2 + 0.5 * (- f1 + f3 + f2) ** 2 + opt["c_accu"] * f4  # stabilized loss
    return loss

In [11]:
class create_dirs:
    """ Creates directories for Checkpoints and saving trained models """

    def __init__(self, ct):
        self.ct = ct
        self.dircp = 'checkpoint.pth_{}.tar'.format(self.ct)
        self.dirout = 'Mul_trained_RKM_{}.tar'.format(self.ct)

    def create(self):
        if not os.path.exists('cp/'):
            os.makedirs('cp/')

        if not os.path.exists('out/'):
            os.makedirs('out/')

    def save_checkpoint(self, state, is_best):
        if is_best:
            torch.save(state, 'cp/{}'.format(self.dircp))

In [12]:
# https://discuss.pytorch.org/t/dataloader-access-two-items-at-the-same-time/22664
class ConcatDataset(torch.utils.data.Dataset):
    def __init__(self, dataset1, dataset2):
#         self.dataset1 = dataset1 # datasets should be sorted!
#         self.dataset2 = dataset2

        self.dataset1 = torch.tensor(dataset1.values) # datasets should be sorted!
        self.dataset2 = torch.tensor(dataset2.values)

    def __getitem__(self, index):
#         x1 = self.dataset1.loc[index].to_numpy() #loc, que no iloc (puede que iloc funcione)
#         x2 = self.dataset2.loc[index].to_numpy()
        
        x1 = self.dataset1[index].float()
        x2 = self.dataset2[index].float()

        return x1, x2, index

    def __len__(self):
        return len(self.dataset1) # assuming both datasets have same length
    
# print("Hello")
train_loader = DataLoader(
             ConcatDataset(rna, atac),
             batch_size=args["batch_size"], shuffle=args["shuffle"],
             num_workers=args["workers"]
            )
# print("There")

# initial_time = datetime.datetime.now()
# for i, (datax, datay, index) in enumerate(train_loader):
#     if i==0:
#         initial_time_first_iteration = datetime.datetime.now()
#     print(i)
#     print(datax.shape)
#     print(datay.shape)
#     if i==2:
#         break
        
# print("It took {} min overall.".format(datetime.datetime.now()-initial_time))
# print("It took {} min from the first iteration.".format(datetime.datetime.now()-initial_time_first_iteration))

# num_workers = 5 -> It took 0:08:38.815087 min.
# num_workers = 15 -> It took 0:11:13.346173 min overall - It took 0:01:15.955870 min from the first iteration.
# num_workers = 24 -> It took 0:16:11.308331 min overall - It took 0:02:02.066693 min from the first iteration
# num_workers = 48 -> It took 0:40:50.197775 min overall - It took 0:04:59.826997 min from the first iteration
# Estos 4 de arriba se han hecho con pandas df, los de abajo con tensores
# num_workers = 0 -> It took 0:00:20.585820 min overall - It took 0:00:13.921048 min from the first iteration
# num_workers = 5 -> It took 0:00:35.032580 min overall - It took 0:00:12.420856 min from the first iteration
# num_workers = 15 -> It took 0:00:47.020544 min overall - It took 0:00:05.366418 min from the first iteration
# num_workers = 24 -> It took 0:02:04.082042 min overall - It took 0:00:07.720705 min from the first iteration.
# num_workers = 24 -> It took 0:01:13.212152 min overall - It took 0:00:17.465964 min from the first iteration.
# num_workers = 48 -> It took 0:03:54.132624 min overall - It took 0:00:42.083046 min from the first iteration

## Setting up the NNs

In [13]:
# class Net1(nn.Module): # Phi 1 - RNA to feature map
#     def __init__(self, input_dim, hidden_dim, args):
#         super(Net1, self).__init__()
# #         c = capacity
#         self.linear1 = nn.Linear(in_features=input_dim, out_features=hidden_dim)
#         self.linear2 = nn.Linear(in_features=hidden_dim, out_features=args["x_fdim"])


#     def forward(self, x):
#         x = self.linear1(x)
#         x = F.leaky_relu(x, negative_slope=0.2)
#         x = self.linear2(x)
# #         x = F.leaky_relu(x, negative_slope=0.2)

#         return x

class Net1(nn.Module): # Phi 1 - RNA to feature map
    def __init__(self, input_dim, hidden_dim_list, args):
        super(Net1, self).__init__()
        
        self.transformations = nn.ModuleList()
        self.transformations.append(nn.Linear(in_features=input_dim, out_features=hidden_dim_list[0]))
        
        for i in range(len(hidden_dim_list)):
            if i == len(hidden_dim_list)-1:
                dim = hidden_dim_list[-1]
                self.transformations.append(nn.Linear(in_features=dim, out_features=args["x_fdim"]))
                
            else:
                in_dim, out_dim = hidden_dim_list[i], hidden_dim_list[i+1]
                self.transformations.append(nn.Linear(in_features=in_dim, out_features=out_dim))
        
    def forward(self, x):
        for i, transform in enumerate(self.transformations):
            if i == len(self.transformations)-1:
                x = transform(x)
                # No leaky relu at the end
                
            else:
                x = transform(x)
                x = F.leaky_relu(x, negative_slope=0.2)
        return x
    
    
# class Net3(nn.Module):
#     def __init__(self, input_dim, hidden_dim, args): #Psi 1 - Feature map to RNA (input dim = 5000)
#         super(Net3, self).__init__()
#         self.linear2t = nn.Linear(in_features=args["x_fdim"], out_features=hidden_dim)
#         self.linear1t = nn.Linear(in_features=hidden_dim, out_features=input_dim)

#     def forward(self, x):
#         x = self.linear2t(x)
#         x = F.leaky_relu(x, negative_slope=0.2)
#         x = self.linear1t(x)
#         x = F.relu(x) # RNA preprocessed has a lower bound of 0

#         return x
    
class Net3(nn.Module):
    def __init__(self, input_dim, hidden_dim_list, args): #Psi 1 - Feature map to RNA (input dim = 5000)
        super(Net3, self).__init__()
        
        hidden_dim_list.reverse() # Reverse the list to be the inverse of Net 1
        self.reverse_transformations = nn.ModuleList()
        self.reverse_transformations.append(nn.Linear(in_features=args["x_fdim"], out_features=hidden_dim_list[0]))
        
        for i in range(len(hidden_dim_list)):
            if i == len(hidden_dim_list)-1:
                dim = hidden_dim_list[-1]
                self.reverse_transformations.append(nn.Linear(in_features=dim, out_features=input_dim))
                
            else:
                in_dim, out_dim = hidden_dim_list[i], hidden_dim_list[i+1]
                self.reverse_transformations.append(nn.Linear(in_features=in_dim, out_features=out_dim))
        
    def forward(self, x):
        for i, transform in enumerate(self.reverse_transformations):
            if i == len(self.reverse_transformations)-1:
                x = transform(x)
                x = F.relu(x) # RNA preprocessed has a lower bound of 0
                
            else:
                x = transform(x)
                x = F.leaky_relu(x, negative_slope=0.2)
                
        return x

In [14]:
class Net2(nn.Module): # Phi 2 - ATAC to feature map
    def __init__(self, input_dim, hidden_dim_list, args): 
        super(Net2, self).__init__()
#         c = capacity
        self.transformations = nn.ModuleList()
        self.transformations.append(nn.Linear(in_features=input_dim, out_features=hidden_dim_list[0]))
        
        for i in range(len(hidden_dim_list)):
            if i == len(hidden_dim_list)-1:
                dim = hidden_dim_list[-1]
                self.transformations.append(nn.Linear(in_features=dim, out_features=args["x_fdim"]))
                
            else:
                in_dim, out_dim = hidden_dim_list[i], hidden_dim_list[i+1]
                self.transformations.append(nn.Linear(in_features=in_dim, out_features=out_dim))
        
    def forward(self, x):
        for i, transform in enumerate(self.transformations):
            if i == len(self.transformations)-1:
                x = transform(x)
                # No leaky relu at the end
                
            else:
                x = transform(x)
                x = F.leaky_relu(x, negative_slope=0.2)
                
        return x

# class Net2(nn.Module): # Phi 2 - ATAC to feature map
#     def __init__(self, input_dim, hidden_dim_list, args): 
#         super(Net2, self).__init__()
# #         c = capacity
#         self.linear1 = nn.Linear(in_features=input_dim,out_features=hidden_dim_list[0])
#         self.linear2 = nn.Linear(in_features=hidden_dim_list[0], out_features=hidden_dim_list[1])
#         self.linear3 = nn.Linear(in_features=hidden_dim_list[1], out_features=args["y_fdim"])


#     def forward(self, x):
#         x = self.linear1(x)
#         x = F.leaky_relu(x, negative_slope=0.2)
#         x = self.linear2(x)
#         x = F.leaky_relu(x, negative_slope=0.2)
#         x = self.linear3(x)        
# #         x = F.leaky_relu(x, negative_slope=0.2)

#         return x   

class Net4(nn.Module):
    def __init__(self, input_dim, hidden_dim_list, args): #Psi 2 - Feature map to ATAC (input dim = 116490)
        super(Net4, self).__init__()
    
        hidden_dim_list.reverse() # Reverse the list to be the inverse of Net 2
        self.reverse_transformations = nn.ModuleList()
        self.reverse_transformations.append(nn.Linear(in_features=args["x_fdim"], out_features=hidden_dim_list[0]))
        
        for i in range(len(hidden_dim_list)):
            if i == len(hidden_dim_list)-1:
                dim = hidden_dim_list[-1]
                self.reverse_transformations.append(nn.Linear(in_features=dim, out_features=input_dim))
                
            else:
                in_dim, out_dim = hidden_dim_list[i], hidden_dim_list[i+1]
                self.reverse_transformations.append(nn.Linear(in_features=in_dim, out_features=out_dim))
        
    def forward(self, x):
        for i, transform in enumerate(self.reverse_transformations):
            if i == len(self.reverse_transformations)-1:
                x = transform(x)
                x = torch.sigmoid(x) # ATAC is has binary values
                
            else:
                x = transform(x)
                x = F.leaky_relu(x, negative_slope=0.2)   
                
        return x
        
# class Net4(nn.Module):
#     def __init__(self, input_dim, hidden_dim_list, args): #Psi 2 - Feature map to ATAC (input dim = 116490)
#         super(Net4, self).__init__()        
#         self.linear3t = nn.Linear(in_features=args["y_fdim"], out_features=hidden_dim_list[1])
#         self.linear2t = nn.Linear(in_features=hidden_dim_list[1], out_features=hidden_dim_list[0])
#         self.linear1t = nn.Linear(in_features=hidden_dim_list[0], out_features=input_dim)

#     def forward(self, x):
#         x = self.linear3t(x)
#         x = F.leaky_relu(x, negative_slope=0.2)
#         x = self.linear2t(x)
#         x = F.leaky_relu(x, negative_slope=0.2)
#         x = self.linear1t(x)
#         x = torch.sigmoid(x) # ATAC is has binary values

#         return x    

In [15]:
# args = {"x_fdim":2}
# hid = [1000, 500, 300, 200, 50, 10]
# inp = 10000
# n2 = Net2(inp, hid, args)
# n4 = Net4(inp, hid, args)
# print(n2.transformations)
# print(n4.reverse_transformations)

In [16]:
def final_compute(data, net1, net2, kPCA, device=torch.device("cuda" if torch.cuda.is_available() else "cpu")):
    """ Function to compute embeddings of full dataset. """
    # Data is a dictionary with keys RNA and ATAC
#     args["shuffle"] = False
#     xt, _, _ = get_mnist_dataloader(args=args)  # loading data without shuffle
    xt = data["RNA"]
    yt = data["ATAC"]
    xtr = net1(xt.to(args.device))
    ytr = net2(yt.to(args.device)) # This was targets at first, but we don't have labels

    h, s = kPCA(xtr, ytr)
    return torch.mm(torch.t(xtr), h), torch.mm(torch.t(ytr), h), h, s

## Initialize nets and parameters

In [17]:
# net1 = Net1(input_dim=5000, hidden_dim=1000, args=args).float().to(opt["device"]) # input_dim, hidden_dim, args
# net2 = Net2(input_dim=116490, hidden_dim_list=[10000, 2000], args=args).float().to(opt["device"]) # input_dim, hidden_dim_list, args
# net3 = Net3(input_dim=5000, hidden_dim=1000, args=args).float().to(opt["device"]) # input_dim, hidden_dim, args
# net4 = Net4(input_dim=116490, hidden_dim_list=[10000, 2000], args=args).float().to(opt["device"]) # input_dim, hidden_dim_list, args
# net4 = Net4(input_dim=116490, hidden_dim_list=[10000, 2000], args=args).double().to(opt["device"])

hidden_list_rna = [3000, 1000, 500, 64]
hidden_list_atac = [5000, 2500, 1000, 500, 64]
net1 = Net1(input_dim=5000, hidden_dim_list=hidden_list_rna, args=args).float().to(opt["device"]) # input_dim, hidden_dim, args
net2 = Net2(input_dim=10002, hidden_dim_list=hidden_list_atac, args=args).float().to(opt["device"]) # input_dim, hidden_dim_list, args
net3 = Net3(input_dim=5000, hidden_dim_list=hidden_list_rna, args=args).float().to(opt["device"]) # input_dim, hidden_dim, args
net4 = Net4(input_dim=10002, hidden_dim_list=hidden_list_atac, args=args).float().to(opt["device"])

params = list(net1.parameters()) + list(net3.parameters()) + list(net2.parameters()) + list(net4.parameters())
optimizer = torch.optim.Adam(params, lr=opt["lr"], weight_decay=0)

## Train

In [18]:
ct = time.strftime("%Y%m%d-%H%M")
dirs = create_dirs(ct=ct)
dirs.create()

In [ ]:
l_cost = 6  # Costs from where checkpoints will be saved
t = 1
cost = np.inf  # Initialize cost
start = datetime.datetime.now()
while cost > 0.2 and t <= opt["max_epochs"]:  # run epochs until convergence
    avg_loss = 0
    for i, (datax, datay, _) in enumerate(train_loader):
        if i < math.ceil(opt["N"] / opt["batch_size"]):
#             print(f'On step {i}', end="\r")
            print(f'On step {i}')
            datax, datay = datax.float().to(opt["device"]), datay.float().to(opt["device"])
            output1 = net1(datax.float())
#             print(f"output1: {output1}")
            output2 = net2(datay.float())
#             print(f"output2: {output2}")
            loss = rkm_loss(output1, datax, output2, datay).float()

            optimizer.zero_grad()
            loss.backward()
            nn.utils.clip_grad_norm_(parameters=params, max_norm=1)
            optimizer.step()
            avg_loss += loss.detach().cpu().numpy()
        
        else:
            break
    cost = avg_loss

    # Remember lowest cost and save checkpoint
    is_best = cost < l_cost
    l_cost = min(cost, l_cost)

    dirs.save_checkpoint({
        'epochs': t + 1,
        'net1_state_dict': net1.state_dict(),
        'net3_state_dict': net3.state_dict(),
        'net2_state_dict': net2.state_dict(),
        'net4_state_dict': net4.state_dict(),
        'l_cost': l_cost,
        'optimizer': optimizer.state_dict()}, is_best)
    print(f"Epoch: {t}, Cost: {cost}")
    t += 1
print('Finished Training in: {}. Lowest cost: {}'.format(str(datetime.datetime.now() - start), l_cost))

On step 0
output1: tensor([[ 0.0677, -0.0815,  0.0509,  ...,  0.0914,  0.1114,  0.0039],
        [ 0.0700, -0.0889,  0.0497,  ...,  0.0921,  0.1081,  0.0183],
        [ 0.0753, -0.0915,  0.0521,  ...,  0.0927,  0.1175,  0.0089],
        ...,
        [ 0.0823, -0.0832,  0.0546,  ...,  0.0976,  0.1055,  0.0086],
        [ 0.0779, -0.0800,  0.0516,  ...,  0.0936,  0.1047,  0.0117],
        [ 0.0775, -0.0906,  0.0529,  ...,  0.0915,  0.1122,  0.0067]],
       grad_fn=<AddmmBackward0>)
output2: tensor([[-0.0083,  0.0688,  0.0278,  ...,  0.0922,  0.1153,  0.1241],
        [-0.0135,  0.0760,  0.0296,  ...,  0.0933,  0.1205,  0.1223],
        [-0.0118,  0.0696,  0.0281,  ...,  0.0920,  0.1140,  0.1226],
        ...,
        [-0.0085,  0.0770,  0.0277,  ...,  0.0934,  0.1222,  0.1207],
        [-0.0103,  0.0707,  0.0289,  ...,  0.0920,  0.1159,  0.1238],
        [-0.0101,  0.0708,  0.0284,  ...,  0.0918,  0.1152,  0.1229]],
       grad_fn=<AddmmBackward0>)
tensor([[ 1.9912e-03, -1.5557e-04, -1.

On step 6
output1: tensor([[ 0.0735, -0.0800,  0.0537,  ...,  0.0964,  0.1128,  0.0055],
        [ 0.0706, -0.0885,  0.0507,  ...,  0.0947,  0.1083,  0.0057],
        [ 0.0767, -0.0838,  0.0540,  ...,  0.0966,  0.1037,  0.0063],
        ...,
        [ 0.0693, -0.0846,  0.0480,  ...,  0.0984,  0.1164,  0.0078],
        [ 0.0736, -0.0900,  0.0456,  ...,  0.1008,  0.1127,  0.0019],
        [ 0.0756, -0.0876,  0.0457,  ...,  0.0945,  0.1058,  0.0084]],
       grad_fn=<AddmmBackward0>)
output2: tensor([[-0.0104,  0.0731,  0.0314,  ...,  0.0961,  0.1196,  0.1232],
        [-0.0084,  0.0772,  0.0248,  ...,  0.0921,  0.1194,  0.1202],
        [-0.0080,  0.0707,  0.0277,  ...,  0.0925,  0.1190,  0.1253],
        ...,
        [-0.0093,  0.0685,  0.0271,  ...,  0.0939,  0.1174,  0.1218],
        [-0.0052,  0.0714,  0.0282,  ...,  0.0928,  0.1207,  0.1224],
        [-0.0115,  0.0699,  0.0262,  ...,  0.0955,  0.1151,  0.1211]],
       grad_fn=<AddmmBackward0>)
tensor([[ 1.7589e-03,  1.0514e-04,  9.

On step 12
output1: tensor([[ 0.0734, -0.0825,  0.0498,  ...,  0.0887,  0.1125,  0.0081],
        [ 0.0698, -0.0830,  0.0519,  ...,  0.0891,  0.1109,  0.0142],
        [ 0.0780, -0.0911,  0.0464,  ...,  0.1045,  0.1026, -0.0016],
        ...,
        [ 0.0685, -0.0842,  0.0402,  ...,  0.0984,  0.1046,  0.0025],
        [ 0.0697, -0.0817,  0.0485,  ...,  0.0970,  0.1097,  0.0014],
        [ 0.0767, -0.0862,  0.0462,  ...,  0.0969,  0.1114,  0.0119]],
       grad_fn=<AddmmBackward0>)
output2: tensor([[-0.0079,  0.0720,  0.0244,  ...,  0.0938,  0.1169,  0.1202],
        [-0.0107,  0.0686,  0.0302,  ...,  0.0924,  0.1171,  0.1220],
        [-0.0121,  0.0740,  0.0311,  ...,  0.0955,  0.1179,  0.1235],
        ...,
        [-0.0106,  0.0735,  0.0254,  ...,  0.0942,  0.1173,  0.1238],
        [-0.0081,  0.0735,  0.0292,  ...,  0.0956,  0.1239,  0.1222],
        [-0.0079,  0.0692,  0.0291,  ...,  0.0946,  0.1183,  0.1233]],
       grad_fn=<AddmmBackward0>)
tensor([[ 2.6963e-03,  5.4741e-04,  3

On step 18
output1: tensor([[ 0.0705, -0.0804,  0.0480,  ...,  0.0920,  0.1155,  0.0122],
        [ 0.0818, -0.0851,  0.0550,  ...,  0.0922,  0.1107, -0.0038],
        [ 0.0724, -0.0832,  0.0505,  ...,  0.0970,  0.1089,  0.0079],
        ...,
        [ 0.0770, -0.0849,  0.0544,  ...,  0.0956,  0.1048,  0.0130],
        [ 0.0725, -0.0833,  0.0482,  ...,  0.0943,  0.1115,  0.0087],
        [ 0.0743, -0.0840,  0.0508,  ...,  0.0982,  0.1117,  0.0086]],
       grad_fn=<AddmmBackward0>)
output2: tensor([[-0.0092,  0.0701,  0.0277,  ...,  0.0934,  0.1151,  0.1244],
        [-0.0118,  0.0706,  0.0278,  ...,  0.0935,  0.1145,  0.1212],
        [-0.0083,  0.0715,  0.0282,  ...,  0.0934,  0.1172,  0.1208],
        ...,
        [-0.0093,  0.0659,  0.0288,  ...,  0.0950,  0.1160,  0.1217],
        [-0.0109,  0.0736,  0.0284,  ...,  0.0957,  0.1218,  0.1225],
        [-0.0118,  0.0691,  0.0285,  ...,  0.0938,  0.1143,  0.1235]],
       grad_fn=<AddmmBackward0>)
tensor([[ 2.0630e-03,  1.2970e-04,  7

On step 24
output1: tensor([[ 0.0718, -0.0892,  0.0548,  ...,  0.0957,  0.1051,  0.0103],
        [ 0.0778, -0.0804,  0.0412,  ...,  0.0982,  0.1078,  0.0158],
        [ 0.0752, -0.0790,  0.0502,  ...,  0.1000,  0.1080,  0.0052],
        ...,
        [ 0.0742, -0.0882,  0.0449,  ...,  0.0957,  0.1068,  0.0148],
        [ 0.0778, -0.0968,  0.0512,  ...,  0.1077,  0.1055,  0.0138],
        [ 0.0752, -0.0871,  0.0489,  ...,  0.0950,  0.1108,  0.0122]],
       grad_fn=<AddmmBackward0>)
output2: tensor([[-0.0109,  0.0724,  0.0268,  ...,  0.0944,  0.1197,  0.1241],
        [-0.0117,  0.0746,  0.0268,  ...,  0.0929,  0.1162,  0.1204],
        [-0.0096,  0.0726,  0.0295,  ...,  0.0941,  0.1180,  0.1235],
        ...,
        [-0.0085,  0.0694,  0.0281,  ...,  0.0926,  0.1193,  0.1214],
        [-0.0101,  0.0681,  0.0257,  ...,  0.0937,  0.1142,  0.1247],
        [-0.0111,  0.0713,  0.0315,  ...,  0.0936,  0.1181,  0.1275]],
       grad_fn=<AddmmBackward0>)
tensor([[ 2.8225e-03, -7.3099e-04, -1

On step 30
output1: tensor([[ 0.0768, -0.0812,  0.0520,  ...,  0.0906,  0.1076,  0.0130],
        [ 0.0754, -0.0892,  0.0480,  ...,  0.0977,  0.1068,  0.0060],
        [ 0.0789, -0.0896,  0.0418,  ...,  0.0948,  0.1067,  0.0083],
        ...,
        [ 0.0654, -0.0945,  0.0392,  ...,  0.1082,  0.1102, -0.0027],
        [ 0.0717, -0.0793,  0.0521,  ...,  0.0889,  0.1111,  0.0045],
        [ 0.0784, -0.0867,  0.0521,  ...,  0.1043,  0.1072, -0.0055]],
       grad_fn=<AddmmBackward0>)
output2: tensor([[-0.0118,  0.0743,  0.0319,  ...,  0.0965,  0.1199,  0.1219],
        [-0.0109,  0.0733,  0.0325,  ...,  0.0910,  0.1179,  0.1249],
        [-0.0103,  0.0734,  0.0300,  ...,  0.0949,  0.1182,  0.1246],
        ...,
        [-0.0081,  0.0708,  0.0271,  ...,  0.0925,  0.1179,  0.1234],
        [-0.0110,  0.0722,  0.0308,  ...,  0.0922,  0.1211,  0.1267],
        [-0.0104,  0.0743,  0.0292,  ...,  0.0960,  0.1197,  0.1224]],
       grad_fn=<AddmmBackward0>)
tensor([[ 2.5564e-03, -3.2902e-05, -1

On step 36
output1: tensor([[ 0.0749, -0.0860,  0.0525,  ...,  0.0870,  0.1075,  0.0106],
        [ 0.0724, -0.0804,  0.0503,  ...,  0.0960,  0.1072,  0.0106],
        [ 0.0695, -0.0840,  0.0513,  ...,  0.0971,  0.1156, -0.0002],
        ...,
        [ 0.0755, -0.0853,  0.0532,  ...,  0.0918,  0.1055,  0.0151],
        [ 0.0765, -0.0794,  0.0490,  ...,  0.0943,  0.1139,  0.0009],
        [ 0.0757, -0.0866,  0.0472,  ...,  0.0937,  0.1087,  0.0116]],
       grad_fn=<AddmmBackward0>)
output2: tensor([[-0.0096,  0.0693,  0.0281,  ...,  0.0933,  0.1158,  0.1211],
        [-0.0079,  0.0743,  0.0281,  ...,  0.0950,  0.1205,  0.1229],
        [-0.0103,  0.0718,  0.0277,  ...,  0.0963,  0.1173,  0.1256],
        ...,
        [-0.0091,  0.0700,  0.0281,  ...,  0.0931,  0.1155,  0.1236],
        [-0.0098,  0.0742,  0.0282,  ...,  0.0977,  0.1223,  0.1239],
        [-0.0115,  0.0694,  0.0291,  ...,  0.0929,  0.1185,  0.1238]],
       grad_fn=<AddmmBackward0>)
tensor([[ 1.8576e-03,  7.3910e-05, -5

On step 42
output1: tensor([[ 0.0610, -0.1096,  0.0346,  ...,  0.0991,  0.1083,  0.0029],
        [ 0.0747, -0.0821,  0.0491,  ...,  0.0934,  0.1094,  0.0093],
        [ 0.0752, -0.0832,  0.0515,  ...,  0.1013,  0.1152,  0.0044],
        ...,
        [ 0.0705, -0.0810,  0.0553,  ...,  0.0910,  0.1102,  0.0074],
        [ 0.0807, -0.0970,  0.0465,  ...,  0.1000,  0.1018,  0.0003],
        [ 0.0702, -0.0850,  0.0412,  ...,  0.0928,  0.1055,  0.0125]],
       grad_fn=<AddmmBackward0>)
output2: tensor([[-0.0086,  0.0716,  0.0289,  ...,  0.0966,  0.1193,  0.1237],
        [-0.0045,  0.0754,  0.0247,  ...,  0.0970,  0.1217,  0.1238],
        [-0.0108,  0.0736,  0.0234,  ...,  0.0935,  0.1140,  0.1229],
        ...,
        [-0.0103,  0.0696,  0.0281,  ...,  0.0943,  0.1182,  0.1248],
        [-0.0090,  0.0712,  0.0292,  ...,  0.0938,  0.1187,  0.1229],
        [-0.0122,  0.0689,  0.0288,  ...,  0.0958,  0.1153,  0.1239]],
       grad_fn=<AddmmBackward0>)
tensor([[ 1.2198e-02, -4.3666e-04,  1

On step 48
output1: tensor([[ 0.0756, -0.0877,  0.0502,  ...,  0.0929,  0.1060,  0.0036],
        [ 0.0790, -0.0830,  0.0428,  ...,  0.1006,  0.1058,  0.0069],
        [ 0.0758, -0.0845,  0.0477,  ...,  0.0960,  0.1109,  0.0093],
        ...,
        [ 0.0755, -0.0843,  0.0507,  ...,  0.0972,  0.1074,  0.0094],
        [ 0.0778, -0.0835,  0.0513,  ...,  0.0982,  0.0991,  0.0049],
        [ 0.0722, -0.0844,  0.0512,  ...,  0.0906,  0.1100,  0.0086]],
       grad_fn=<AddmmBackward0>)
output2: tensor([[-0.0069,  0.0714,  0.0289,  ...,  0.0924,  0.1184,  0.1243],
        [-0.0072,  0.0730,  0.0288,  ...,  0.0949,  0.1219,  0.1233],
        [-0.0106,  0.0705,  0.0292,  ...,  0.0961,  0.1184,  0.1226],
        ...,
        [-0.0092,  0.0761,  0.0283,  ...,  0.0954,  0.1176,  0.1225],
        [-0.0077,  0.0705,  0.0274,  ...,  0.0924,  0.1169,  0.1241],
        [-0.0071,  0.0710,  0.0299,  ...,  0.0945,  0.1177,  0.1232]],
       grad_fn=<AddmmBackward0>)
tensor([[ 2.2663e-03, -2.3246e-05,  2

On step 54
output1: tensor([[ 8.2981e-02, -9.2680e-02,  5.1409e-02,  ...,  9.9781e-02,
          1.0777e-01,  9.7240e-03],
        [ 7.5499e-02, -7.9662e-02,  4.8611e-02,  ...,  1.0074e-01,
          1.1214e-01,  8.0782e-03],
        [ 7.9814e-02, -9.4869e-02,  3.9229e-02,  ...,  1.0013e-01,
          1.0851e-01,  4.6504e-03],
        ...,
        [ 7.9848e-02, -7.7721e-02,  5.5792e-02,  ...,  9.7797e-02,
          1.0314e-01,  5.5068e-05],
        [ 7.4027e-02, -8.1667e-02,  5.5165e-02,  ...,  9.6638e-02,
          1.1229e-01,  9.3686e-03],
        [ 7.5215e-02, -8.0931e-02,  5.2552e-02,  ...,  9.5197e-02,
          1.0634e-01,  1.0835e-02]], grad_fn=<AddmmBackward0>)
output2: tensor([[-0.0086,  0.0696,  0.0279,  ...,  0.0929,  0.1156,  0.1239],
        [-0.0102,  0.0715,  0.0327,  ...,  0.0910,  0.1208,  0.1265],
        [-0.0068,  0.0709,  0.0246,  ...,  0.0938,  0.1191,  0.1248],
        ...,
        [-0.0085,  0.0752,  0.0294,  ...,  0.0905,  0.1191,  0.1259],
        [-0.0104,  0

In [ ]:
# # net1(datax.float())
# output1 = net1(datax.double()).double()
# output2 = net2(datay.double()).double()
# print(output1)
# print(output2)
# loss = rkm_loss(output1, datax, output2, datay).double()
# print(loss)

In [ ]:
# # https://discuss.pytorch.org/t/train-simultaneously-on-two-datasets/649
# # class ConcatDataset(torch.utils.data.Dataset):
# #     def __init__(self, *datasets):
# # #         self.datasets = datasets
# #         self.datasets = [torch.tensor(dataset.values) for dataset in datasets]

# #     def __getitem__(self, i):
# #         return tuple(d[i] for d in self.datasets)

# #     def __len__(self):
# #         return min(len(d) for d in self.datasets)

# # import multiprocessing

# # %time
# # https://discuss.pytorch.org/t/dataloader-access-two-items-at-the-same-time/22664
# class ConcatDataset(torch.utils.data.Dataset):
#     def __init__(self, dataset1, dataset2):
# #         self.dataset1 = dataset1 # datasets should be sorted!
# #         self.dataset2 = dataset2

#         self.dataset1 = torch.tensor(dataset1.values) # datasets should be sorted!
#         self.dataset2 = torch.tensor(dataset2.values)

#     def __getitem__(self, index):
# #         print(index)
# #         print(type(index))
# #         print(type(self.dataset1.loc[index].values))
# #         x1 = self.dataset1.loc[index].to_numpy() #loc, que no iloc (puede que iloc funcione)
# #         x2 = self.dataset2.loc[index].to_numpy()
        
#         x1 = self.dataset1[index]
#         x2 = self.dataset2[index]

#         return x1, x2, index

#     def __len__(self):
#         return len(self.dataset1) # assuming both datasets have same length

# print("Hello")
# train_loader = DataLoader(
#              ConcatDataset(rna, atac),
#              batch_size=args["batch_size"], shuffle=args["shuffle"],
#              num_workers=48 #args["workers"]
#             )
# print("There")

# initial_time = datetime.datetime.now()
# for i, (datax, datay, index) in enumerate(train_loader):
#     if i==0:
#         initial_time_first_iteration = datetime.datetime.now()
#     print(i)
#     print(datax.shape)
#     print(datay.shape)
#     if i==2:
#         break
        
# print("It took {} min overall.".format(datetime.datetime.now()-initial_time))
# print("It took {} min from the first iteration.".format(datetime.datetime.now()-initial_time_first_iteration))

# num_workers = 5 -> It took 0:08:38.815087 min.
# num_workers = 15 -> It took 0:11:13.346173 min overall - It took 0:01:15.955870 min from the first iteration.
# num_workers = 24 -> It took 0:16:11.308331 min overall - It took 0:02:02.066693 min from the first iteration
# num_workers = 48 -> It took 0:40:50.197775 min overall - It took 0:04:59.826997 min from the first iteration
# Estos 4 de arriba se han hecho con pandas df, los de abajo con tensores
# num_workers = 0 -> It took 0:00:20.585820 min overall - It took 0:00:13.921048 min from the first iteration
# num_workers = 5 -> It took 0:00:35.032580 min overall - It took 0:00:12.420856 min from the first iteration
# num_workers = 15 -> It took 0:00:47.020544 min overall - It took 0:00:05.366418 min from the first iteration
# num_workers = 24 -> It took 0:02:04.082042 min overall - It took 0:00:07.720705 min from the first iteration.
# num_workers = 24 -> It took 0:01:13.212152 min overall - It took 0:00:17.465964 min from the first iteration.
# num_workers = 48 -> It took 0:03:54.132624 min overall - It took 0:00:42.083046 min from the first iteration