In [1]:
import numpy as np
import pandas as pd
# import adata
import matplotlib.pyplot as plt
import seaborn as sns
import scanpy as sc
import os
import datetime
import argparse
import torch
from utils import *
from torch.utils.data import DataLoader

## Loading data

For more information check this [link](https://openproblems.bio/neurips_docs/about_tasks/task3_joint_embedding/)

In [2]:
# data
# !ls ~/arc_00077/raw_data/phase2-data/joint_embedding/openproblems_bmmc_multiome_phase2
# ! cd ~/arc_00077/raw_data/phase2-data/joint_embedding/openproblems_bmmc_multiome_phase2
! ls /user/leuven/331/vsc33180/arc_00077/raw_data/phase2-data/joint_embedding/openproblems_bmmc_multiome_phase2

openproblems_bmmc_multiome_phase2.censor_dataset.output_mod1.h5ad
openproblems_bmmc_multiome_phase2.censor_dataset.output_mod2.h5ad
openproblems_bmmc_multiome_phase2.censor_dataset.output_solution.h5ad


In [3]:
os.listdir("/user/leuven/331/vsc33180/arc_00077/raw_data/phase2-data/joint_embedding/openproblems_bmmc_multiome_phase2/")

['openproblems_bmmc_multiome_phase2.censor_dataset.output_mod1.h5ad',
 'openproblems_bmmc_multiome_phase2.censor_dataset.output_mod2.h5ad',
 'openproblems_bmmc_multiome_phase2.censor_dataset.output_solution.h5ad']

In [4]:
data_folder_path = "/user/leuven/331/vsc33180/arc_00077/raw_data/phase2-data/joint_embedding/openproblems_bmmc_multiome_phase2/"
files = os.listdir(data_folder_path)
# print(data_folder_path + files[0])
data1 = sc.read_h5ad(data_folder_path + files[0])
data2 = sc.read(data_folder_path + files[1])
# data3 = sc.read(data_folder_path + files[2])

Only considering the two last: ['.output_mod2', '.h5ad'].
Only considering the two last: ['.output_mod2', '.h5ad'].


In [5]:
print(data1)
print(data2)

AnnData object with n_obs × n_vars = 42492 × 13431
    obs: 'batch', 'size_factors'
    var: 'gene_ids', 'feature_types'
    uns: 'dataset_id', 'organism'
    layers: 'counts'
AnnData object with n_obs × n_vars = 42492 × 116490
    obs: 'batch'
    var: 'feature_types'
    uns: 'dataset_id', 'gene_activity_var_names', 'organism'
    obsm: 'gene_activity'
    layers: 'counts'


In [6]:
# print(data1.var["feature_types"])
rna = pd.DataFrame.sparse.from_spmatrix(data1.X) # 42492 x 13431
rna.columns = data1.var.index #data1.var["gene_ids"] -> ENSEMBL IDs

sc.pp.highly_variable_genes(data1, n_top_genes=5000) # Find HGVs
rna = rna.transpose().loc[data1.var["highly_variable"] == True].transpose()
rna.head() # 42492 x 5000

LINC01128  KLHL17  ISG15  C1orf159    CDK11B  SLC35E2B  CDK11A  PEX10  \
0        0.0     0.0    0.0       0.0  0.000000       0.0     0.0    0.0   
1        0.0     0.0    0.0       0.0  1.161511       0.0     0.0    0.0   
2        0.0     0.0    0.0       0.0  0.000000       0.0     0.0    0.0   
3        0.0     0.0    0.0       0.0  0.000000       0.0     0.0    0.0   
4        0.0     0.0    0.0       0.0  0.000000       0.0     0.0    0.0   

   PLCH2  TPRG1L  ...   MT-ATP8   MT-ATP6    MT-CO3    MT-ND3   MT-ND4L  \
0    0.0     0.0  ...  0.000000  0.000000  0.000000  1.688304  0.000000   
1    0.0     0.0  ...  0.000000  0.000000  1.161511  0.000000  0.000000   
2    0.0     0.0  ...  0.344029  0.599516  1.455109  0.344029  0.344029   
3    0.0     0.0  ...  0.000000  1.355826  2.527316  0.000000  0.000000   
4    0.0     0.0  ...  0.000000  1.556855  2.646429  1.054988  0.000000   

     MT-ND4    MT-ND5    MT-ND6    MT-CYB  AL592183.1  
0  1.688304  0.000000  0.000000  1.688304         0.0  
1  0.000000  0.000000  0.000000  2.651025         0.0  
2  0.599516  0.802834  0.344029  1.455109         0.0  
3  0.000000  1.911013  0.000000  0.000000         0.0  
4  1.556855  1.054988  0.000000  2.337923         0.0  

[5 rows x 5000 columns]

In [7]:
atac = pd.DataFrame.sparse.from_spmatrix(data2.X)
atac.columns = data2.var.index
atac.head() # 42492 x 116490

chr1-9776-10668  chr1-180726-181005  chr1-181117-181803  \
0              0.0                 0.0                 0.0   
1              0.0                 0.0                 0.0   
2              0.0                 0.0                 0.0   
3              0.0                 0.0                 0.0   
4              0.0                 0.0                 0.0   

   chr1-191133-192055  chr1-267562-268456  chr1-629497-630394  \
0                 0.0                 0.0                 0.0   
1                 0.0                 0.0                 1.0   
2                 0.0                 0.0                 0.0   
3                 0.0                 0.0                 0.0   
4                 0.0                 0.0                 0.0   

   chr1-633515-634474  chr1-778276-779191  chr1-816868-817761  \
0                 1.0                 0.0                 0.0   
1                 1.0                 0.0                 0.0   
2                 1.0                 0.0                 0.0   
3                 0.0                 0.0                 0.0   
4                 1.0                 0.0                 0.0   

   chr1-822804-823597  ...  GL000195.1-137376-138301  GL000219.1-39933-40839  \
0                 0.0  ...                       0.0                     0.0   
1                 0.0  ...                       0.0                     0.0   
2                 0.0  ...                       0.0                     0.0   
3                 0.0  ...                       0.0                     0.0   
4                 0.0  ...                       0.0                     0.0   

   GL000219.1-42172-43054  GL000219.1-44703-45584  GL000219.1-45726-46450  \
0                     0.0                     0.0                     0.0   
1                     0.0                     0.0                     0.0   
2                     0.0                     0.0                     0.0   
3                     0.0                     0.0                     0.0   
4                     0.0                     0.0                     0.0   

   GL000219.1-90062-90937  GL000219.1-99257-100160  KI270726.1-27152-28034  \
0                     0.0                      1.0                     0.0   
1                     0.0                      0.0                     0.0   
2                     0.0                      0.0                     0.0   
3                     0.0                      0.0                     0.0   
4                     0.0                      0.0                     0.0   

   KI270713.1-21434-22336  KI270713.1-29629-30491  
0                     0.0                     0.0  
1                     0.0                     0.0  
2                     0.0                     0.0  
3                     0.0                     0.0  
4                     0.0                     0.0  

[5 rows x 116490 columns]

## Setting up the necessary arguments and functions

In [8]:
# %tb
# # Model Settings =================================================================================================
# parser = argparse.ArgumentParser(description='Gen-RKM Model')

# parser.add_argument('--N', type=int, default=1000, help='Total # of samples')
# parser.add_argument('--mb_size', type=int, default=300, help='Mini-batch size. See utils.py')
# parser.add_argument('--h_dim', type=int, default=2, help='Dim of latent vector') # shared latent space
# parser.add_argument('--capacity', type=int, default=32, help='Capacity of network. See utils.py') # important in CNNs
# parser.add_argument('--x_fdim', type=int, default=128, help='Input x_fdim. See utils.py') # feature map dimensionality
# parser.add_argument('--y_fdim', type=int, default=20, help='Input y_fdim. See utils.py') # feature map dimensionality
# parser.add_argument('--c_accu', type=float, default=100, help='Input weight on recons_error')

# # Training Settings =============================
# parser.add_argument('--lr', type=float, default=1e-4, help='Input learning rate for optimizer')
# parser.add_argument('--max_epochs', type=int, default=100, help='Input max_epoch for cut-off')
# # parser.add_argument('--device', type=str, default='cuda', help='Device type: cuda or cpu')
# parser.add_argument('--device', type=str, default='cuda' if torch.cuda.is_available() else 'cpu', help='Device type: cuda or cpu')
# parser.add_argument('--workers', type=int, default=0, help='# of workers for dataloader')
# parser.add_argument('--shuffle', type=bool, default=True, help='shuffle dataset: true or false')

# opt = parser.parse_args()
args = {
    "N": rna.shape[0],
#     "mb_size": 300,
    "h_dim": 32,
    "capacity": 32,
    "x_fdim": 128,
    "y_fdim": 256,
    "c_accu": 100,
    "lr": 1e-6,
    "max_epochs": 1,
    "device": torch.device("cuda" if torch.cuda.is_available() else "cpu"),
    "workers": 15,
    "shuffle": True,
    "batch_size": 100,
}
opt = args
# print(opt["mb_size"])

In [9]:
def kPCA(X, Y):
#     print(X)
#     print(Y)
    a = torch.mm(X, torch.t(X)) + torch.mm(Y, torch.t(Y))
    nh1 = a.size(0)
    oneN = torch.div(torch.ones(nh1, nh1), nh1).float().to(opt["device"])
    a = a - torch.mm(oneN, a) - torch.mm(a, oneN) + torch.mm(torch.mm(oneN, a), oneN)  # centering
    print(a)
#     print(a, end="\r")
    h, s, _ = torch.svd(a, some=False)
    return h[:, :opt["h_dim"]], s

In [10]:
# Energy function
def rkm_loss(output1, X, output2, Y):
    h, s = kPCA(output1, output2)
    U = torch.mm(torch.t(output1), h)
    V = torch.mm(torch.t(output2), h)

    x_tilde = net3(torch.mm(h, torch.t(U))) # NET3
    y_tilde = net4(torch.mm(h, torch.t(V))) # NET4

    # Costs
    f1 = torch.trace(torch.mm(torch.mm(output1, U), torch.t(h))) + torch.trace(
        torch.mm(torch.mm(output2, V), torch.t(h)))
    f2 = 0.5 * torch.trace(torch.mm(h, torch.mm(torch.diag(s[:opt["h_dim"]]), torch.t(h))))
    f3 = 0.5 * ((torch.trace(torch.mm(torch.t(U), U))) + (torch.trace(torch.mm(torch.t(V), V))))
    recon_loss = torch.nn.MSELoss()
    f4 = recon_loss(x_tilde, X) + recon_loss(y_tilde, Y)  # reconstruction loss

    loss = - f1 + f3 + f2 + 0.5 * (- f1 + f3 + f2) ** 2 + opt["c_accu"] * f4  # stabilized loss
    return loss

In [11]:
class create_dirs:
    """ Creates directories for Checkpoints and saving trained models """

    def __init__(self, ct):
        self.ct = ct
        self.dircp = 'checkpoint.pth_{}.tar'.format(self.ct)
        self.dirout = 'Mul_trained_RKM_{}.tar'.format(self.ct)

    def create(self):
        if not os.path.exists('cp/'):
            os.makedirs('cp/')

        if not os.path.exists('out/'):
            os.makedirs('out/')

    def save_checkpoint(self, state, is_best):
        if is_best:
            torch.save(state, 'cp/{}'.format(self.dircp))

In [12]:
# https://discuss.pytorch.org/t/dataloader-access-two-items-at-the-same-time/22664
class ConcatDataset(torch.utils.data.Dataset):
    def __init__(self, dataset1, dataset2):
#         self.dataset1 = dataset1 # datasets should be sorted!
#         self.dataset2 = dataset2

        self.dataset1 = torch.tensor(dataset1.values) # datasets should be sorted!
        self.dataset2 = torch.tensor(dataset2.values)

    def __getitem__(self, index):
#         x1 = self.dataset1.loc[index].to_numpy() #loc, que no iloc (puede que iloc funcione)
#         x2 = self.dataset2.loc[index].to_numpy()
        
        x1 = self.dataset1[index].float()
        x2 = self.dataset2[index].float()

        return x1, x2, index

    def __len__(self):
        return len(self.dataset1) # assuming both datasets have same length
    
# print("Hello")
train_loader = DataLoader(
             ConcatDataset(rna, atac),
             batch_size=args["batch_size"], shuffle=args["shuffle"],
             num_workers=args["workers"]
            )
# print("There")

# initial_time = datetime.datetime.now()
# for i, (datax, datay, index) in enumerate(train_loader):
#     if i==0:
#         initial_time_first_iteration = datetime.datetime.now()
#     print(i)
#     print(datax.shape)
#     print(datay.shape)
#     if i==2:
#         break
        
# print("It took {} min overall.".format(datetime.datetime.now()-initial_time))
# print("It took {} min from the first iteration.".format(datetime.datetime.now()-initial_time_first_iteration))

# num_workers = 5 -> It took 0:08:38.815087 min.
# num_workers = 15 -> It took 0:11:13.346173 min overall - It took 0:01:15.955870 min from the first iteration.
# num_workers = 24 -> It took 0:16:11.308331 min overall - It took 0:02:02.066693 min from the first iteration
# num_workers = 48 -> It took 0:40:50.197775 min overall - It took 0:04:59.826997 min from the first iteration
# Estos 4 de arriba se han hecho con pandas df, los de abajo con tensores
# num_workers = 0 -> It took 0:00:20.585820 min overall - It took 0:00:13.921048 min from the first iteration
# num_workers = 5 -> It took 0:00:35.032580 min overall - It took 0:00:12.420856 min from the first iteration
# num_workers = 15 -> It took 0:00:47.020544 min overall - It took 0:00:05.366418 min from the first iteration
# num_workers = 24 -> It took 0:02:04.082042 min overall - It took 0:00:07.720705 min from the first iteration.
# num_workers = 24 -> It took 0:01:13.212152 min overall - It took 0:00:17.465964 min from the first iteration.
# num_workers = 48 -> It took 0:03:54.132624 min overall - It took 0:00:42.083046 min from the first iteration

## Setting up the NNs

In [13]:
class Net1(nn.Module): # Phi 1 - RNA to feature map
    def __init__(self, input_dim, hidden_dim, args):
        super(Net1, self).__init__()
#         c = capacity
        self.linear1 = nn.Linear(in_features=input_dim,out_features=hidden_dim)
        self.linear2 = nn.Linear(in_features=hidden_dim,out_features=args["x_fdim"])


    def forward(self, x):
        x = self.linear1(x)
        x = F.leaky_relu(x, negative_slope=0.2)
        x = self.linear2(x)
#         x = F.leaky_relu(x, negative_slope=0.2)

        return x   

class Net3(nn.Module):
    def __init__(self, input_dim, hidden_dim, args): #Psi 1 - Feature map to RNA (input dim = 5000)
        super(Net3, self).__init__()
        self.linear2t = nn.Linear(in_features=args["x_fdim"],out_features=hidden_dim)
        self.linear1t = nn.Linear(in_features=hidden_dim,out_features=input_dim)

    def forward(self, x):
        x = self.linear2t(x)
        x = F.leaky_relu(x, negative_slope=0.2)
        x = self.linear1t(x)
        x = F.relu(x) # RNA preprocessed has a lower bound of 0

        return x    

In [14]:
class Net2(nn.Module): # Phi 2 - ATAC to feature map
    def __init__(self, input_dim, hidden_dim_list, args): # Expects a 2D list
        super(Net2, self).__init__()
        assert len(hidden_dim_list) == 2
#         c = capacity
        self.linear1 = nn.Linear(in_features=input_dim,out_features=hidden_dim_list[0])
        self.linear2 = nn.Linear(in_features=hidden_dim_list[0], out_features=hidden_dim_list[1])
        self.linear3 = nn.Linear(in_features=hidden_dim_list[1], out_features=args["y_fdim"])


    def forward(self, x):
        x = self.linear1(x)
        x = F.leaky_relu(x, negative_slope=0.2)
        x = self.linear2(x)
        x = F.leaky_relu(x, negative_slope=0.2)
        x = self.linear3(x)        
#         x = F.leaky_relu(x, negative_slope=0.2)

        return x   

class Net4(nn.Module):
    def __init__(self, input_dim, hidden_dim_list, args): #Psi 2 - Feature map to ATAC (input dim = 116490)
        super(Net4, self).__init__()
        assert len(hidden_dim_list) == 2
        self.linear3t = nn.Linear(in_features=args["y_fdim"], out_features=hidden_dim_list[1])
        self.linear2t = nn.Linear(in_features=hidden_dim_list[1], out_features=hidden_dim_list[0])
        self.linear1t = nn.Linear(in_features=hidden_dim_list[0], out_features=input_dim)

    def forward(self, x):
        x = self.linear3t(x)
        x = F.leaky_relu(x, negative_slope=0.2)
        x = self.linear2t(x)
        x = F.leaky_relu(x, negative_slope=0.2)
        x = self.linear1t(x)
        x = torch.sigmoid(x) # ATAC is has binary values

        return x    

In [15]:
def final_compute(data, net1, net2, kPCA, device=torch.device("cuda" if torch.cuda.is_available() else "cpu")):
    """ Function to compute embeddings of full dataset. """
    # Data is a dictionary with keys RNA and ATAC
#     args["shuffle"] = False
#     xt, _, _ = get_mnist_dataloader(args=args)  # loading data without shuffle
    xt = data["RNA"]
    yt = data["ATAC"]
    xtr = net1(xt.to(args.device))
    ytr = net2(yt.to(args.device)) # This was targets at first, but we don't have labels

    h, s = kPCA(xtr, ytr)
    return torch.mm(torch.t(xtr), h), torch.mm(torch.t(ytr), h), h, s

## Initialize nets and parameters

In [16]:
net1 = Net1(input_dim=5000, hidden_dim=1000, args=args).float().to(opt["device"]) # input_dim, hidden_dim, args
net2 = Net2(input_dim=116490, hidden_dim_list=[10000, 2000], args=args).float().to(opt["device"]) # input_dim, hidden_dim_list, args
net3 = Net3(input_dim=5000, hidden_dim=1000, args=args).float().to(opt["device"]) # input_dim, hidden_dim, args
net4 = Net4(input_dim=116490, hidden_dim_list=[10000, 2000], args=args).float().to(opt["device"]) # input_dim, hidden_dim_list, args
# net4 = Net4(input_dim=116490, hidden_dim_list=[10000, 2000], args=args).double().to(opt["device"])

params = list(net1.parameters()) + list(net3.parameters()) + list(net2.parameters()) + list(net4.parameters())
optimizer = torch.optim.Adam(params, lr=opt["lr"], weight_decay=0)

## Train

In [17]:
ct = time.strftime("%Y%m%d-%H%M")
dirs = create_dirs(ct=ct)
dirs.create()

In [18]:
l_cost = 6  # Costs from where checkpoints will be saved
t = 1
cost = np.inf  # Initialize cost
start = datetime.datetime.now()
while cost > 0.2 and t <= opt["max_epochs"]:  # run epochs until convergence
    avg_loss = 0
    for i, (datax, datay, _) in enumerate(train_loader):
        if i < math.ceil(opt["N"] / opt["batch_size"]):
#             print(f'On step {i}', end="\r")
            print(f'On step {i}')
            datax, datay = datax.float().to(opt["device"]), datay.float().to(opt["device"])
            output1 = net1(datax.float())
            output2 = net2(datay.float())
            loss = rkm_loss(output1, datax, output2, datay).float()

            optimizer.zero_grad()
            loss.backward()
            nn.utils.clip_grad_norm_(parameters=params, max_norm=1)
            optimizer.step()
            avg_loss += loss.detach().cpu().numpy()
        
        else:
            break
    cost = avg_loss

    # Remember lowest cost and save checkpoint
    is_best = cost < l_cost
    l_cost = min(cost, l_cost)

    dirs.save_checkpoint({
        'epochs': t + 1,
        'net1_state_dict': net1.state_dict(),
        'net3_state_dict': net3.state_dict(),
        'net2_state_dict': net2.state_dict(),
        'net4_state_dict': net4.state_dict(),
        'l_cost': l_cost,
        'optimizer': optimizer.state_dict()}, is_best)
    print(f"Epoch: {t}, Cost: {cost}")
    t += 1
print('Finished Training in: {}. Lowest cost: {}'.format(str(datetime.datetime.now() - start), l_cost))

On step 0
tensor([[ 0.7026, -0.1300,  0.1406,  ..., -0.0771,  0.0545,  0.0237],
        [-0.1300,  0.9599, -0.2249,  ...,  0.0334, -0.1598, -0.1799],
        [ 0.1406, -0.2249,  0.7324,  ...,  0.0163, -0.0846,  0.0187],
        ...,
        [-0.0771,  0.0334,  0.0163,  ...,  0.4323, -0.0913, -0.0031],
        [ 0.0545, -0.1598, -0.0846,  ..., -0.0913,  0.6327,  0.0411],
        [ 0.0237, -0.1799,  0.0187,  ..., -0.0031,  0.0411,  0.5989]],
       grad_fn=<AddBackward0>)
On step 1
tensor([[ 0.4765,  0.0028,  0.0628,  ..., -0.1020,  0.0726,  0.0232],
        [ 0.0028,  0.5028, -0.0814,  ..., -0.0945, -0.0174, -0.0337],
        [ 0.0628, -0.0814,  0.9231,  ...,  0.2493, -0.1218, -0.0925],
        ...,
        [-0.1020, -0.0945,  0.2493,  ...,  1.1034, -0.1691, -0.0218],
        [ 0.0726, -0.0174, -0.1218,  ..., -0.1691,  0.4794,  0.0519],
        [ 0.0232, -0.0337, -0.0925,  ..., -0.0218,  0.0519,  0.5117]],
       grad_fn=<AddBackward0>)
On step 2
tensor([[ 0.4177, -0.0536,  0.0732,  ...

On step 17
tensor([[ 0.8772,  0.0418,  0.3157,  ..., -0.1343, -0.0737, -0.0302],
        [ 0.0418,  0.3717,  0.0834,  ..., -0.0522, -0.0081,  0.0434],
        [ 0.3157,  0.0834,  0.9268,  ..., -0.1447, -0.0546,  0.1042],
        ...,
        [-0.1343, -0.0522, -0.1447,  ...,  0.7024, -0.0200, -0.0708],
        [-0.0737, -0.0081, -0.0546,  ..., -0.0200,  0.3348, -0.0035],
        [-0.0302,  0.0434,  0.1042,  ..., -0.0708, -0.0035,  0.4280]],
       grad_fn=<AddBackward0>)
On step 18
tensor([[ 7.6233e-01, -1.4089e-01, -1.0006e-01,  ..., -3.8441e-02,
          4.1453e-03, -1.0668e-01],
        [-1.4089e-01,  5.4304e-01,  1.0143e-01,  ...,  1.3953e-01,
          2.5681e-02,  4.7926e-02],
        [-1.0006e-01,  1.0143e-01,  5.8601e-01,  ..., -1.5492e-02,
         -9.8415e-02,  7.1591e-04],
        ...,
        [-3.8441e-02,  1.3953e-01, -1.5492e-02,  ...,  1.0039e+00,
          7.4123e-03, -3.8440e-02],
        [ 4.1453e-03,  2.5681e-02, -9.8415e-02,  ...,  7.4123e-03,
          6.4863e-01,

On step 34
tensor([[ 0.4456,  0.0181,  0.1146,  ...,  0.0285, -0.0363, -0.0212],
        [ 0.0181,  0.4639, -0.0850,  ...,  0.0708,  0.0295,  0.0188],
        [ 0.1146, -0.0850,  0.6742,  ..., -0.0551, -0.0957, -0.0218],
        ...,
        [ 0.0285,  0.0708, -0.0551,  ...,  0.4952, -0.0220,  0.0101],
        [-0.0363,  0.0295, -0.0957,  ..., -0.0220,  0.8103,  0.0769],
        [-0.0212,  0.0188, -0.0218,  ...,  0.0101,  0.0769,  0.4380]],
       grad_fn=<AddBackward0>)
On step 35
tensor([[ 0.4309, -0.0158,  0.0556,  ..., -0.0826, -0.0064,  0.0412],
        [-0.0158,  1.0891, -0.0566,  ...,  0.0627,  0.2490, -0.0460],
        [ 0.0556, -0.0566,  0.4781,  ..., -0.0587, -0.0642,  0.0855],
        ...,
        [-0.0826,  0.0627, -0.0587,  ...,  0.6892,  0.1082, -0.0652],
        [-0.0064,  0.2490, -0.0642,  ...,  0.1082,  0.7755, -0.0236],
        [ 0.0412, -0.0460,  0.0855,  ..., -0.0652, -0.0236,  0.5537]],
       grad_fn=<AddBackward0>)
On step 36
tensor([[ 6.7370e-01, -2.3507e-02, -3

On step 50
tensor([[ 1.7407e+00, -1.3939e-01, -2.5295e-01,  ..., -5.9831e-02,
         -7.2100e-02,  6.3486e-02],
        [-1.3939e-01,  5.3684e-01,  2.7123e-02,  ..., -1.2056e-01,
          1.9468e-02, -1.1296e-02],
        [-2.5295e-01,  2.7123e-02,  8.6174e-01,  ...,  1.8893e-01,
         -1.2137e-03, -4.0227e-02],
        ...,
        [-5.9831e-02, -1.2056e-01,  1.8893e-01,  ...,  8.3102e-01,
          2.1821e-02, -9.2477e-02],
        [-7.2100e-02,  1.9468e-02, -1.2137e-03,  ...,  2.1821e-02,
          5.9720e-01, -3.0807e-04],
        [ 6.3486e-02, -1.1296e-02, -4.0227e-02,  ..., -9.2477e-02,
         -3.0807e-04,  4.6216e-01]], grad_fn=<AddBackward0>)
On step 51
tensor([[ 0.4727,  0.0129, -0.0460,  ..., -0.0891,  0.1146,  0.0072],
        [ 0.0129,  0.5640, -0.0596,  ..., -0.1557, -0.1299,  0.0174],
        [-0.0460, -0.0596,  0.7313,  ..., -0.0108, -0.0585, -0.1261],
        ...,
        [-0.0891, -0.1557, -0.0108,  ...,  1.7244, -0.1224, -0.1507],
        [ 0.1146, -0.1299, -0

On step 66
tensor([[ 0.5641, -0.0502, -0.0609,  ...,  0.0727,  0.0393, -0.1744],
        [-0.0502,  0.7119, -0.0962,  ..., -0.0334, -0.0939, -0.0801],
        [-0.0609, -0.0962,  0.5526,  ..., -0.0347,  0.0941,  0.0310],
        ...,
        [ 0.0727, -0.0334, -0.0347,  ...,  0.5141,  0.0270, -0.2873],
        [ 0.0393, -0.0939,  0.0941,  ...,  0.0270,  0.3621, -0.0142],
        [-0.1744, -0.0801,  0.0310,  ..., -0.2873, -0.0142,  1.9740]],
       grad_fn=<AddBackward0>)
On step 67
tensor([[ 0.9858,  0.0664, -0.1088,  ..., -0.0976, -0.0315, -0.0369],
        [ 0.0664,  0.6355,  0.0342,  ..., -0.0500,  0.0374,  0.0311],
        [-0.1088,  0.0342,  0.4894,  ...,  0.0602, -0.0060, -0.0396],
        ...,
        [-0.0976, -0.0500,  0.0602,  ...,  0.5658,  0.0183, -0.0146],
        [-0.0315,  0.0374, -0.0060,  ...,  0.0183,  0.5710,  0.0736],
        [-0.0369,  0.0311, -0.0396,  ..., -0.0146,  0.0736,  0.7284]],
       grad_fn=<AddBackward0>)
On step 68
tensor([[ 0.5490, -0.0191,  0.1209,  

On step 82
tensor([[ 0.5342,  0.0621,  0.0073,  ..., -0.0629, -0.0746, -0.0546],
        [ 0.0621,  0.5849, -0.1071,  ..., -0.1810, -0.0743, -0.1892],
        [ 0.0073, -0.1071,  2.1438,  ...,  0.1071, -0.1631, -0.2064],
        ...,
        [-0.0629, -0.1810,  0.1071,  ...,  1.0503,  0.0876,  0.0271],
        [-0.0746, -0.0743, -0.1631,  ...,  0.0876,  0.4682,  0.0190],
        [-0.0546, -0.1892, -0.2064,  ...,  0.0271,  0.0190,  0.9583]],
       grad_fn=<AddBackward0>)
On step 83
tensor([[ 0.7130, -0.0172, -0.0724,  ..., -0.1122, -0.0243,  0.0826],
        [-0.0172,  0.5393,  0.1023,  ..., -0.0514, -0.0820, -0.0379],
        [-0.0724,  0.1023,  0.5425,  ...,  0.0648, -0.0812,  0.0681],
        ...,
        [-0.1122, -0.0514,  0.0648,  ...,  0.7393, -0.0322, -0.0271],
        [-0.0243, -0.0820, -0.0812,  ..., -0.0322,  0.5906, -0.0063],
        [ 0.0826, -0.0379,  0.0681,  ..., -0.0271, -0.0063,  0.4982]],
       grad_fn=<AddBackward0>)
On step 84
tensor([[ 0.8175, -0.0388,  0.1091,  

tensor([[ 1.4731, -0.0092, -0.1650,  ..., -0.0612, -0.0098, -0.1244],
        [-0.0092,  0.6064, -0.0973,  ...,  0.0641,  0.0324, -0.1373],
        [-0.1650, -0.0973,  0.6031,  ..., -0.0991,  0.0237,  0.0676],
        ...,
        [-0.0612,  0.0641, -0.0991,  ...,  1.1601, -0.1826,  0.1273],
        [-0.0098,  0.0324,  0.0237,  ..., -0.1826,  0.6709, -0.0949],
        [-0.1244, -0.1373,  0.0676,  ...,  0.1273, -0.0949,  0.7390]],
       grad_fn=<AddBackward0>)
On step 99
tensor([[ 0.5281, -0.2197,  0.1040,  ..., -0.1595,  0.1629, -0.1220],
        [-0.2197,  2.4264,  0.0102,  ...,  0.5289, -0.0537,  0.1614],
        [ 0.1040,  0.0102,  1.1057,  ...,  0.1631,  0.0332, -0.1397],
        ...,
        [-0.1595,  0.5289,  0.1631,  ...,  1.7170, -0.1323, -0.0388],
        [ 0.1629, -0.0537,  0.0332,  ..., -0.1323,  0.5359, -0.1859],
        [-0.1220,  0.1614, -0.1397,  ..., -0.0388, -0.1859,  1.0253]],
       grad_fn=<AddBackward0>)
On step 100
tensor([[ 0.5195, -0.1098, -0.0471,  ...,  0.02

On step 115
tensor([[ 0.7522, -0.3921,  0.0715,  ...,  0.4965,  0.0672,  0.0526],
        [-0.3921,  1.3507, -0.1591,  ..., -0.6498, -0.1666, -0.0561],
        [ 0.0715, -0.1591,  0.5194,  ...,  0.2137, -0.0166, -0.0726],
        ...,
        [ 0.4965, -0.6498,  0.2137,  ...,  1.6871,  0.3234,  0.0176],
        [ 0.0672, -0.1666, -0.0166,  ...,  0.3234,  0.5973,  0.1012],
        [ 0.0526, -0.0561, -0.0726,  ...,  0.0176,  0.1012,  0.7798]],
       grad_fn=<AddBackward0>)
On step 116
tensor([[ 1.6106, -0.3315, -0.2816,  ..., -0.1128, -0.6539,  0.3537],
        [-0.3315,  0.6557, -0.0093,  ..., -0.0877,  0.2502, -0.0176],
        [-0.2816, -0.0093,  0.7633,  ..., -0.0143,  0.0765, -0.1012],
        ...,
        [-0.1128, -0.0877, -0.0143,  ...,  0.7439,  0.0439, -0.1315],
        [-0.6539,  0.2502,  0.0765,  ...,  0.0439,  0.8709, -0.2228],
        [ 0.3537, -0.0176, -0.1012,  ..., -0.1315, -0.2228,  0.7277]],
       grad_fn=<AddBackward0>)
On step 117
tensor([[ 1.1914, -0.3417, -0.0452

On step 132
tensor([[ 7.6611e-01, -1.0257e-03, -5.4815e-02,  ..., -1.3885e-01,
          6.7417e-02,  5.9792e-02],
        [-1.0257e-03,  1.0312e+00, -4.8319e-02,  ..., -7.3007e-01,
          5.1718e-01,  5.2060e-01],
        [-5.4815e-02, -4.8319e-02,  6.4605e-01,  ...,  2.6421e-01,
         -1.6465e-01, -1.4546e-01],
        ...,
        [-1.3885e-01, -7.3007e-01,  2.6421e-01,  ...,  3.3968e+00,
         -2.4773e+00, -1.9218e+00],
        [ 6.7417e-02,  5.1718e-01, -1.6465e-01,  ..., -2.4773e+00,
          3.1782e+00,  1.4941e+00],
        [ 5.9792e-02,  5.2060e-01, -1.4546e-01,  ..., -1.9218e+00,
          1.4941e+00,  1.9272e+00]], grad_fn=<AddBackward0>)
On step 133
tensor([[ 1.3287, -0.8603,  1.2296,  ..., -0.1317,  0.4996, -0.8192],
        [-0.8603,  1.5686, -1.1777,  ...,  0.0986, -0.4421,  0.7273],
        [ 1.2296, -1.1777,  2.0958,  ..., -0.1932,  0.6487, -1.3095],
        ...,
        [-0.1317,  0.0986, -0.1932,  ...,  0.6162, -0.2003,  0.1697],
        [ 0.4996, -0.4421, 

tensor([[14.3605, -7.7319, -2.5299,  ..., -1.4674,  7.2148,  4.4073],
        [-7.7319,  5.0582,  1.4348,  ...,  0.7359, -4.1470, -2.5877],
        [-2.5299,  1.4348,  1.0152,  ...,  0.3790, -1.4071, -0.8009],
        ...,
        [-1.4674,  0.7359,  0.3790,  ...,  0.8923, -0.7223, -0.3793],
        [ 7.2148, -4.1470, -1.4071,  ..., -0.7223,  4.7689,  2.5293],
        [ 4.4073, -2.5877, -0.8009,  ..., -0.3793,  2.5293,  2.2641]],
       grad_fn=<AddBackward0>)
On step 148
tensor([[  9.9930,  -2.0980, -10.6582,  ...,  -0.6515,   4.1465,   1.9919],
        [ -2.0980,   1.0631,   2.4012,  ...,   0.2519,  -1.0269,  -0.4395],
        [-10.6582,   2.4012,  12.8271,  ...,   0.6558,  -4.8241,  -1.9418],
        ...,
        [ -0.6515,   0.2519,   0.6558,  ...,   0.5254,  -0.2902,  -0.1625],
        [  4.1465,  -1.0269,  -4.8241,  ...,  -0.2902,   3.1236,   0.7096],
        [  1.9919,  -0.4395,  -1.9418,  ...,  -0.1625,   0.7096,   1.0138]],
       grad_fn=<AddBackward0>)
On step 149
tensor([[ 

On step 163
tensor([[ 3.1771, -2.4556, -1.6808,  ..., -2.7653,  6.2428, -0.2655],
        [-2.4556,  2.8852,  1.4542,  ...,  2.5327, -5.5806,  0.0851],
        [-1.6808,  1.4542,  1.6246,  ...,  1.6267, -3.9113, -0.0849],
        ...,
        [-2.7653,  2.5327,  1.6267,  ...,  3.3669, -6.2098,  0.1481],
        [ 6.2428, -5.5806, -3.9113,  ..., -6.2098, 14.7595, -0.1989],
        [-0.2655,  0.0851, -0.0849,  ...,  0.1481, -0.1989,  1.3971]],
       grad_fn=<AddBackward0>)
On step 164
tensor([[ 84.4896, -25.4949,  -7.2418,  ..., -54.0048, -24.0620,   7.1067],
        [-25.4949,   8.1471,   2.2420,  ...,  16.3208,   7.2879,  -2.0820],
        [ -7.2418,   2.2420,   1.4008,  ...,   4.3604,   2.1264,  -0.5810],
        ...,
        [-54.0048,  16.3208,   4.3604,  ...,  36.9084,  16.1036,  -4.7333],
        [-24.0620,   7.2879,   2.1264,  ...,  16.1036,   8.0435,  -2.0945],
        [  7.1067,  -2.0820,  -0.5810,  ...,  -4.7333,  -2.0945,   1.2684]],
       grad_fn=<AddBackward0>)
On step 16

On step 179
tensor([[  1.6689,   1.0490,  -0.5531,  ...,  -4.0157,   7.6300,  -1.9826],
        [  1.0490,   2.4063,  -0.9141,  ...,  -4.9608,   9.5834,  -2.0439],
        [ -0.5531,  -0.9141,   1.0544,  ...,   2.7258,  -5.0328,   1.1508],
        ...,
        [ -4.0157,  -4.9608,   2.7258,  ...,  17.3070, -32.1881,   7.7318],
        [  7.6300,   9.5834,  -5.0328,  ..., -32.1881,  62.7155, -14.7655],
        [ -1.9826,  -2.0439,   1.1508,  ...,   7.7318, -14.7655,   4.3470]],
       grad_fn=<AddBackward0>)
On step 180
tensor([[  2.2501,  11.8571,  -0.8427,  ...,   5.4859,   1.4257,  -7.9320],
        [ 11.8571,  99.6342,  -7.1071,  ...,  44.1251,  10.9322, -64.8948],
        [ -0.8427,  -7.1071,   0.9227,  ...,  -3.0379,  -0.7370,   4.5027],
        ...,
        [  5.4859,  44.1251,  -3.0379,  ...,  20.9377,   5.3165, -29.9651],
        [  1.4257,  10.9322,  -0.7370,  ...,   5.3165,   1.8358,  -7.6133],
        [ -7.9320, -64.8948,   4.5027,  ..., -29.9651,  -7.6133,  44.1948]],
     

On step 195
tensor([[  2.1763,   3.2127,  -9.3376,  ...,   5.7842,  -5.4460, -12.9389],
        [  3.2127,   7.0359, -18.1019,  ...,  11.4555, -10.7896, -25.5510],
        [ -9.3376, -18.1019,  53.4311,  ..., -33.2068,  31.2352,  72.9307],
        ...,
        [  5.7842,  11.4555, -33.2068,  ...,  22.1668, -19.6870, -46.2685],
        [ -5.4460, -10.7896,  31.2351,  ..., -19.6870,  19.8907,  44.2301],
        [-12.9389, -25.5510,  72.9307,  ..., -46.2685,  44.2301, 104.5945]],
       grad_fn=<AddBackward0>)
On step 196
tensor([[  90.5310, -131.6880,  -14.0499,  ..., -107.8391,    1.8730,
         -107.0228],
        [-131.6880,  193.4836,   20.3850,  ...,  157.7703,   -2.5861,
          156.8429],
        [ -14.0499,   20.3850,    2.8573,  ...,   16.5505,   -0.4475,
           16.5157],
        ...,
        [-107.8391,  157.7703,   16.5505,  ...,  131.3892,   -2.2144,
          128.2394],
        [   1.8729,   -2.5861,   -0.4475,  ...,   -2.2144,    0.7536,
           -1.9767],
       

On step 210
tensor([[  30.2493,   16.5603, -156.8192,  ...,  -28.4406,    3.4383,
          -26.4681],
        [  16.5603,   10.1998,  -87.2646,  ...,  -15.7668,    1.9574,
          -14.7987],
        [-156.8192,  -87.2646,  833.3777,  ...,  150.7420,  -17.0272,
          141.5146],
        ...,
        [ -28.4406,  -15.7668,  150.7420,  ...,   27.7448,   -3.1466,
           25.4998],
        [   3.4383,    1.9574,  -17.0272,  ...,   -3.1466,    1.0060,
           -2.7327],
        [ -26.4681,  -14.7987,  141.5146,  ...,   25.4998,   -2.7327,
           24.5515]], grad_fn=<AddBackward0>)
On step 211
tensor([[  14.6484,   32.4163,  -64.8712,  ...,    8.7303,    5.8706,
          -53.9483],
        [  32.4163,   76.9624, -152.3618,  ...,   20.6895,   14.0815,
         -126.8121],
        [ -64.8712, -152.3618,  304.8258,  ...,  -41.2281,  -28.1109,
          253.2641],
        ...,
        [   8.7303,   20.6896,  -41.2281,  ...,    6.2140,    3.8653,
          -34.3071],
        [   5.8

On step 225
tensor([[ 1.1818e+02,  4.6830e+00, -1.8504e+01,  ...,  1.6843e+02,
         -6.3997e+01,  8.4045e+00],
        [ 4.6830e+00,  1.4659e+00, -5.6430e-01,  ...,  7.0140e+00,
         -2.7297e+00,  2.2946e-01],
        [-1.8504e+01, -5.6430e-01,  3.9308e+00,  ..., -2.6348e+01,
          9.8677e+00, -1.4306e+00],
        ...,
        [ 1.6843e+02,  7.0140e+00, -2.6348e+01,  ...,  2.4159e+02,
         -9.1356e+01,  1.2084e+01],
        [-6.3997e+01, -2.7297e+00,  9.8676e+00,  ..., -9.1356e+01,
          3.5313e+01, -4.4634e+00],
        [ 8.4045e+00,  2.2943e-01, -1.4306e+00,  ...,  1.2084e+01,
         -4.4634e+00,  1.1091e+00]], grad_fn=<AddBackward0>)
On step 226
tensor([[ 242.2040,  139.5668,  -80.0044,  ..., -151.8146, -293.3063,
           -7.3987],
        [ 139.5668,   81.6258,  -46.2790,  ...,  -87.7499, -169.3869,
           -4.2854],
        [ -80.0044,  -46.2790,   27.0160,  ...,   50.4481,   96.7757,
            2.4981],
        ...,
        [-151.8146,  -87.7499,   5

On step 239
tensor([[ 156.2302, -112.3473,   75.7384,  ...,  -13.5256,   32.1517,
          237.3518],
        [-112.3473,   81.9024,  -54.8127,  ...,    9.9318,  -23.2954,
         -172.2105],
        [  75.7384,  -54.8127,   37.4546,  ...,   -6.6665,   15.8429,
          115.9586],
        ...,
        [ -13.5257,    9.9317,   -6.6666,  ...,    1.8442,   -2.7284,
          -21.1570],
        [  32.1516,  -23.2954,   15.8428,  ...,   -2.7284,    7.3252,
           49.1468],
        [ 237.3518, -172.2105,  115.9586,  ...,  -21.1570,   49.1468,
          366.1197]], grad_fn=<AddBackward0>)
On step 240
tensor([[  86.0302,   -8.9516, -166.5079,  ...,   -4.5847,  -24.5804,
          180.6956],
        [  -8.9516,    1.6464,   17.7854,  ...,    0.4828,    2.6701,
          -19.1956],
        [-166.5078,   17.7854,  325.4456,  ...,    8.6389,   48.3920,
         -352.3122],
        ...,
        [  -4.5847,    0.4827,    8.6389,  ...,    0.9639,    1.2986,
           -9.6304],
        [ -24.5

On step 254
tensor([[  46.9024,   55.9753, -148.4395,  ..., -131.7881,   61.8158,
         -276.1221],
        [  55.9753,   68.4783, -179.7981,  ..., -159.7278,   75.1083,
         -334.4321],
        [-148.4395, -179.7981,  476.6913,  ...,  423.1722, -199.0034,
          886.0804],
        ...,
        [-131.7881, -159.7278,  423.1722,  ...,  376.3849, -176.8801,
          787.0559],
        [  61.8158,   75.1083, -199.0034,  ..., -176.8801,   84.0753,
         -370.2129],
        [-276.1221, -334.4321,  886.0804,  ...,  787.0559, -370.2129,
         1648.3378]], grad_fn=<AddBackward0>)
On step 255
tensor([[   1.2344,    2.0779,   -4.2263,  ...,   13.6548,    3.3391,
            1.5212],
        [   2.0779,   11.0030,  -22.1707,  ...,   63.9611,   15.9337,
            7.3605],
        [  -4.2263,  -22.1707,   53.8515,  ..., -149.9278,  -38.3294,
          -17.4726],
        ...,
        [  13.6548,   63.9611, -149.9278,  ...,  429.4327,  108.8215,
           49.4664],
        [   3.3

On step 268
tensor([[ 977.7628,   98.8694, -440.3167,  ..., -409.5231,   65.1868,
          328.8292],
        [  98.8694,   10.6215,  -44.5847,  ...,  -41.4066,    6.6802,
           33.2908],
        [-440.3167,  -44.5847,  199.2054,  ...,  184.6642,  -29.3898,
         -147.9853],
        ...,
        [-409.5231,  -41.4066,  184.6642,  ...,  172.4900,  -27.3068,
         -137.7946],
        [  65.1868,    6.6802,  -29.3898,  ...,  -27.3068,    5.0878,
           21.9092],
        [ 328.8292,   33.2908, -147.9853,  ..., -137.7946,   21.9092,
          111.1185]], grad_fn=<AddBackward0>)
On step 269
tensor([[ 175.2828,    3.9385,   77.1379,  ...,  -75.5256,   47.5390,
         -221.8195],
        [   3.9385,    0.9713,    1.7932,  ...,   -1.6041,    0.9720,
           -4.8724],
        [  77.1379,    1.7932,   34.7103,  ...,  -33.2787,   21.0334,
          -97.8827],
        ...,
        [ -75.5257,   -1.6041,  -33.2788,  ...,   33.4933,  -20.5654,
           96.0735],
        [  47.5

On step 283
tensor([[  59.5292,  -65.1857,  -99.1809,  ..., -145.4128,  112.0475,
           -5.4404],
        [ -65.1857,   73.9501,  109.9223,  ...,  161.2974, -124.1937,
            5.7805],
        [ -99.1809,  109.9223,  168.8863,  ...,  246.2438, -189.1677,
            9.1088],
        ...,
        [-145.4129,  161.2974,  246.2438,  ...,  360.8852, -277.1214,
           13.2413],
        [ 112.0475, -124.1937, -189.1677,  ..., -277.1214,  213.8322,
          -10.2525],
        [  -5.4404,    5.7805,    9.1088,  ...,   13.2413,  -10.2525,
            0.9393]], grad_fn=<AddBackward0>)
On step 284
tensor([[  55.1303,   41.5535, -104.3718,  ..., -153.6373,  -17.0324,
           48.7939],
        [  41.5535,   32.0370,  -79.4274,  ..., -116.8790,  -12.9562,
           37.0951],
        [-104.3718,  -79.4274,  200.6852,  ...,  294.2552,   32.3870,
          -93.6761],
        ...,
        [-153.6372, -116.8789,  294.2552,  ...,  433.1358,   47.7046,
         -137.6279],
        [ -17.0

On step 297
tensor([[ 170.6743,  -63.1843, -220.8513,  ..., -199.2197,    1.4309,
          -36.0007],
        [ -63.1843,   24.3677,   81.8411,  ...,   73.9588,   -0.6701,
           13.2760],
        [-220.8513,   81.8411,  287.5060,  ...,  258.9124,   -1.5682,
           46.6314],
        ...,
        [-199.2196,   73.9589,  258.9124,  ...,  234.5635,   -1.0392,
           41.9245],
        [   1.4309,   -0.6700,   -1.5682,  ...,   -1.0392,    1.2488,
           -0.4157],
        [ -36.0007,   13.2760,   46.6314,  ...,   41.9245,   -0.4157,
            8.3987]], grad_fn=<AddBackward0>)
On step 298
tensor([[ 115.5447,  159.6013,   13.1671,  ..., -188.3243,  -91.1759,
           72.4122],
        [ 159.6013,  222.3765,   18.1965,  ..., -261.6129, -126.8374,
          100.6363],
        [  13.1671,   18.1965,    2.1989,  ...,  -21.4943,  -10.4534,
            8.2051],
        ...,
        [-188.3243, -261.6129,  -21.4943,  ...,  309.1621,  149.6782,
         -118.4225],
        [ -91.1

On step 311
tensor([[ 195.9797,   76.9448, -116.3700,  ..., -122.8118,  111.0645,
          -66.5566],
        [  76.9448,   30.9266,  -45.7859,  ...,  -48.5622,   43.7806,
          -26.2269],
        [-116.3700,  -45.7859,   69.9701,  ...,   73.4156,  -66.2337,
           39.6953],
        ...,
        [-122.8118,  -48.5621,   73.4156,  ...,   78.4595,  -70.0308,
           41.9057],
        [ 111.0646,   43.7807,  -66.2336,  ...,  -70.0308,   63.7582,
          -37.8519],
        [ -66.5565,  -26.2268,   39.6954,  ...,   41.9057,  -37.8519,
           23.2402]], grad_fn=<AddBackward0>)
On step 312
tensor([[  89.0421, -132.5372,   -8.0679,  ...,    7.6734,   35.0822,
           15.6224],
        [-132.5372,  198.9097,   12.0495,  ...,  -11.3687,  -52.4818,
          -23.3969],
        [  -8.0679,   12.0495,    1.3169,  ...,   -0.6583,   -3.1014,
           -1.4200],
        ...,
        [   7.6734,  -11.3687,   -0.6583,  ...,    1.4315,    3.0121,
            1.3196],
        [  35.0

On step 325
tensor([[   8.4086,   58.7864,  -26.8687,  ...,   12.0949,   -9.9646,
          -15.6086],
        [  58.7864,  558.8876, -251.3048,  ...,  115.9993,  -90.4217,
         -146.0458],
        [ -26.8687, -251.3047,  114.5376,  ...,  -52.3199,   41.2271,
           66.0371],
        ...,
        [  12.0950,  115.9994,  -52.3199,  ...,   24.7168,  -18.9147,
          -30.3807],
        [  -9.9645,  -90.4216,   41.2271,  ...,  -18.9147,   15.9443,
           23.9879],
        [ -15.6086, -146.0458,   66.0371,  ...,  -30.3807,   23.9879,
           38.9335]], grad_fn=<AddBackward0>)
On step 326
tensor([[ 4.3612e+03, -4.4914e+02,  1.0669e+02,  ...,  1.8496e+02,
          6.8897e+02,  9.5355e+01],
        [-4.4914e+02,  4.6963e+01, -1.1060e+01,  ..., -1.8903e+01,
         -7.1216e+01, -9.7927e+00],
        [ 1.0669e+02, -1.1060e+01,  3.5516e+00,  ...,  4.5805e+00,
          1.7038e+01,  2.1711e+00],
        ...,
        [ 1.8496e+02, -1.8903e+01,  4.5806e+00,  ...,  8.5088e+00,
   

On step 339
tensor([[ 1.7990e+02, -7.9396e+01,  1.2561e-01,  ...,  2.8120e+02,
         -4.9806e+01,  1.2996e+02],
        [-7.9396e+01,  3.5788e+01, -1.6632e-01,  ..., -1.2468e+02,
          2.2041e+01, -5.7660e+01],
        [ 1.2561e-01, -1.6632e-01,  7.4426e-01,  ...,  7.3486e-02,
         -6.4331e-02,  1.2909e-01],
        ...,
        [ 2.8120e+02, -1.2468e+02,  7.3486e-02,  ...,  4.4303e+02,
         -7.8274e+01,  2.0426e+02],
        [-4.9806e+01,  2.2041e+01, -6.4331e-02,  ..., -7.8274e+01,
          1.4345e+01, -3.6366e+01],
        [ 1.2996e+02, -5.7660e+01,  1.2909e-01,  ...,  2.0426e+02,
         -3.6366e+01,  9.6005e+01]], grad_fn=<AddBackward0>)
On step 340
tensor([[ 8.1837e+00,  1.4130e+01, -4.4498e+01,  ...,  3.2153e-01,
         -2.0328e+01, -5.9494e+00],
        [ 1.4130e+01,  3.7211e+01, -1.1238e+02,  ...,  2.2372e+00,
         -5.0823e+01, -1.3844e+01],
        [-4.4498e+01, -1.1238e+02,  3.4722e+02,  ..., -7.1102e+00,
          1.5677e+02,  4.3187e+01],
        ...

On step 353
tensor([[ 2.5103e+02,  2.2288e+02,  1.9396e+02,  ...,  1.4670e+02,
         -2.1021e+00,  6.0342e+02],
        [ 2.2288e+02,  1.9911e+02,  1.7236e+02,  ...,  1.3049e+02,
         -1.9947e+00,  5.3672e+02],
        [ 1.9396e+02,  1.7236e+02,  1.5080e+02,  ...,  1.1353e+02,
         -1.5579e+00,  4.6728e+02],
        ...,
        [ 1.4670e+02,  1.3049e+02,  1.1353e+02,  ...,  8.6303e+01,
         -1.2147e+00,  3.5332e+02],
        [-2.1021e+00, -1.9947e+00, -1.5579e+00,  ..., -1.2147e+00,
          6.8396e-01, -5.1975e+00],
        [ 6.0342e+02,  5.3672e+02,  4.6728e+02,  ...,  3.5332e+02,
         -5.1975e+00,  1.4544e+03]], grad_fn=<AddBackward0>)
On step 354
tensor([[ 10.2543, -16.6996,  -2.0844,  ..., -19.4766,  44.4175,  15.6210],
        [-16.6996,  30.9656,   4.1198,  ...,  34.7025, -79.5842, -27.8544],
        [ -2.0844,   4.1198,   1.3129,  ...,   4.8781, -11.5597,  -4.3378],
        ...,
        [-19.4766,  34.7025,   4.8781,  ...,  41.2079, -92.7714, -33.0815],
   

On step 367
tensor([[237.8565, 175.8421,  61.7258,  ...,  28.5079, -72.5926, 124.2847],
        [175.8420, 133.0095,  46.4468,  ...,  21.3781, -54.1718,  93.4956],
        [ 61.7258,  46.4468,  17.4014,  ...,   7.3227, -19.2320,  32.8774],
        ...,
        [ 28.5078,  21.3780,   7.3226,  ...,   4.3320,  -8.8419,  15.0891],
        [-72.5927, -54.1719, -19.2321,  ...,  -8.8419,  22.8831, -38.3365],
        [124.2847,  93.4955,  32.8773,  ...,  15.0891, -38.3365,  66.6213]],
       grad_fn=<AddBackward0>)
On step 368
tensor([[ 221.4462,  -57.3655,  276.8252,  ..., -188.2158,  627.7731,
          103.6779],
        [ -57.3655,   15.6027,  -71.9199,  ...,   49.0331, -162.9894,
          -26.9166],
        [ 276.8252,  -71.9199,  347.6847,  ..., -236.0748,  787.2134,
          130.0533],
        ...,
        [-188.2158,   49.0331, -236.0748,  ...,  161.2134, -535.1042,
          -88.3594],
        [ 627.7731, -162.9894,  787.2134,  ..., -535.1042, 1786.1620,
          294.9103],
       

On step 381
tensor([[   6.1235,   45.4079,   -8.9353,  ...,  -60.2829,    7.1895,
           15.1924],
        [  45.4080,  372.6906,  -73.6180,  ..., -490.5513,   58.3001,
          123.4406],
        [  -8.9352,  -73.6180,   15.0720,  ...,   97.2006,  -11.5588,
          -24.4003],
        ...,
        [ -60.2828, -490.5513,   97.2006,  ...,  649.8080,  -77.3636,
         -163.2144],
        [   7.1895,   58.3001,  -11.5588,  ...,  -77.3636,    9.9308,
           19.4678],
        [  15.1924,  123.4406,  -24.4003,  ..., -163.2144,   19.4678,
           41.6604]], grad_fn=<AddBackward0>)
On step 382
tensor([[ 1.1352e+02, -1.2239e+00,  2.1084e+01,  ...,  1.8718e+02,
          3.4835e+02, -2.1326e+02],
        [-1.2239e+00,  7.0184e-01, -2.5977e-01,  ..., -1.9673e+00,
         -3.7292e+00,  2.3000e+00],
        [ 2.1084e+01, -2.5977e-01,  4.5547e+00,  ...,  3.4994e+01,
          6.5230e+01, -3.9938e+01],
        ...,
        [ 1.8718e+02, -1.9674e+00,  3.4994e+01,  ...,  3.1052e+02,
   

On step 395
tensor([[  20.2567,  -27.1909,   14.9231,  ...,  -33.1550, -106.3085,
            1.2934],
        [ -27.1908,   38.3082,  -20.5006,  ...,   45.8922,  146.8120,
           -1.9022],
        [  14.9231,  -20.5007,   12.0718,  ...,  -24.8893,  -79.9539,
            0.9756],
        ...,
        [ -33.1549,   45.8922,  -24.8892,  ...,   56.6205,  179.1675,
           -2.3090],
        [-106.3085,  146.8120,  -79.9538,  ...,  179.1675,  576.8193,
           -7.5875],
        [   1.2935,   -1.9022,    0.9757,  ...,   -2.3090,   -7.5875,
            0.6631]], grad_fn=<AddBackward0>)
On step 396
tensor([[   2.1883,    5.1447,  -28.7891,  ...,   10.1428,   42.5160,
           42.9420],
        [   5.1447,   16.6579,  -88.9129,  ...,   32.0590,  131.0568,
          132.2091],
        [ -28.7891,  -88.9129,  503.2815,  ..., -181.3568, -742.4956,
         -748.0573],
        ...,
        [  10.1428,   32.0590, -181.3568,  ...,   67.8638,  267.0042,
          269.6433],
        [  42.5

On step 409
tensor([[ 2.2039e+03,  1.1793e+02, -3.4766e+02,  ..., -5.7631e+02,
          3.3141e+02, -9.3711e+00],
        [ 1.1793e+02,  7.1177e+00, -1.8669e+01,  ..., -3.0980e+01,
          1.7821e+01, -5.4138e-01],
        [-3.4766e+02, -1.8669e+01,  5.5635e+01,  ...,  9.0950e+01,
         -5.2250e+01,  1.3911e+00],
        ...,
        [-5.7631e+02, -3.0980e+01,  9.0950e+01,  ...,  1.5157e+02,
         -8.6645e+01,  2.4706e+00],
        [ 3.3141e+02,  1.7821e+01, -5.2250e+01,  ..., -8.6645e+01,
          5.0436e+01, -1.3905e+00],
        [-9.3710e+00, -5.4126e-01,  1.3912e+00,  ...,  2.4706e+00,
         -1.3905e+00,  8.7585e-01]], grad_fn=<AddBackward0>)
On step 410
tensor([[   56.9141,    75.4960,   148.7079,  ...,   188.4346,  -365.0325,
           -12.6473],
        [   75.4960,   102.5967,   200.2292,  ...,   253.7051,  -491.5065,
           -17.0751],
        [  148.7079,   200.2292,   394.1325,  ...,   499.3361,  -966.7744,
           -33.7797],
        ...,
        [  188.4

On step 423
tensor([[   4.7731,  -55.5804,   -9.5897,  ...,   44.0632,    5.3849,
            6.7412],
        [ -55.5804,  742.7122,  128.9683,  ..., -589.2615,  -70.0500,
          -90.7485],
        [  -9.5897,  128.9683,   22.8699,  ..., -102.3789,  -12.1357,
          -15.8645],
        ...,
        [  44.0633, -589.2613, -102.3788,  ...,  468.7112,   55.6584,
           71.9496],
        [   5.3849,  -70.0499,  -12.1357,  ...,   55.6584,    7.2802,
            8.4984],
        [   6.7413,  -90.7485,  -15.8644,  ...,   71.9496,    8.4984,
           11.9421]], grad_fn=<AddBackward0>)
On step 424
tensor([[ 299.3698, -304.2799,  440.0529,  ..., -137.2611, -410.1500,
          381.4967],
        [-304.2799,  310.5964, -448.2423,  ...,  139.9172,  417.6207,
         -388.5533],
        [ 440.0529, -448.2423,  648.7552,  ..., -202.1422, -604.0593,
          561.7679],
        ...,
        [-137.2611,  139.9172, -202.1422,  ...,   63.9997,  188.3962,
         -175.3828],
        [-410.1

In [19]:
# # net1(datax.float())
# output1 = net1(datax.double()).double()
# output2 = net2(datay.double()).double()
# print(output1)
# print(output2)
# loss = rkm_loss(output1, datax, output2, datay).double()
# print(loss)

In [20]:
# # https://discuss.pytorch.org/t/train-simultaneously-on-two-datasets/649
# # class ConcatDataset(torch.utils.data.Dataset):
# #     def __init__(self, *datasets):
# # #         self.datasets = datasets
# #         self.datasets = [torch.tensor(dataset.values) for dataset in datasets]

# #     def __getitem__(self, i):
# #         return tuple(d[i] for d in self.datasets)

# #     def __len__(self):
# #         return min(len(d) for d in self.datasets)

# # import multiprocessing

# # %time
# # https://discuss.pytorch.org/t/dataloader-access-two-items-at-the-same-time/22664
# class ConcatDataset(torch.utils.data.Dataset):
#     def __init__(self, dataset1, dataset2):
# #         self.dataset1 = dataset1 # datasets should be sorted!
# #         self.dataset2 = dataset2

#         self.dataset1 = torch.tensor(dataset1.values) # datasets should be sorted!
#         self.dataset2 = torch.tensor(dataset2.values)

#     def __getitem__(self, index):
# #         print(index)
# #         print(type(index))
# #         print(type(self.dataset1.loc[index].values))
# #         x1 = self.dataset1.loc[index].to_numpy() #loc, que no iloc (puede que iloc funcione)
# #         x2 = self.dataset2.loc[index].to_numpy()
        
#         x1 = self.dataset1[index]
#         x2 = self.dataset2[index]

#         return x1, x2, index

#     def __len__(self):
#         return len(self.dataset1) # assuming both datasets have same length

# print("Hello")
# train_loader = DataLoader(
#              ConcatDataset(rna, atac),
#              batch_size=args["batch_size"], shuffle=args["shuffle"],
#              num_workers=48 #args["workers"]
#             )
# print("There")

# initial_time = datetime.datetime.now()
# for i, (datax, datay, index) in enumerate(train_loader):
#     if i==0:
#         initial_time_first_iteration = datetime.datetime.now()
#     print(i)
#     print(datax.shape)
#     print(datay.shape)
#     if i==2:
#         break
        
# print("It took {} min overall.".format(datetime.datetime.now()-initial_time))
# print("It took {} min from the first iteration.".format(datetime.datetime.now()-initial_time_first_iteration))

# num_workers = 5 -> It took 0:08:38.815087 min.
# num_workers = 15 -> It took 0:11:13.346173 min overall - It took 0:01:15.955870 min from the first iteration.
# num_workers = 24 -> It took 0:16:11.308331 min overall - It took 0:02:02.066693 min from the first iteration
# num_workers = 48 -> It took 0:40:50.197775 min overall - It took 0:04:59.826997 min from the first iteration
# Estos 4 de arriba se han hecho con pandas df, los de abajo con tensores
# num_workers = 0 -> It took 0:00:20.585820 min overall - It took 0:00:13.921048 min from the first iteration
# num_workers = 5 -> It took 0:00:35.032580 min overall - It took 0:00:12.420856 min from the first iteration
# num_workers = 15 -> It took 0:00:47.020544 min overall - It took 0:00:05.366418 min from the first iteration
# num_workers = 24 -> It took 0:02:04.082042 min overall - It took 0:00:07.720705 min from the first iteration.
# num_workers = 24 -> It took 0:01:13.212152 min overall - It took 0:00:17.465964 min from the first iteration.
# num_workers = 48 -> It took 0:03:54.132624 min overall - It took 0:00:42.083046 min from the first iteration